<ul>
	<li><a href="#recoverPassword"><?= $this->t->_('Recover My Password'); ?></a></li>
</ul>

<div id="#recoverPassword">
	<?= $this->form; ?>
</div>

<script>
	$(document).ready(function(){
		var options = {  
			url: '/admin/auth/resetpassword',
	        success: vkNgineAjaxFormSubmit,
			dataType : 'json'		
	    };
	    	    
		$('#<?= $this->form->getId(); ?>').ajaxForm(options);
	});
</script>
			