<script type="text/javascript">
$(document).ready(function() {
	$("#sort-table").tablesorter({
		widgets: ['zebra'],
		headers: { 
			0: { sorter: false },
			4: { sorter: false },
			5: { sorter: false },
			6: { sorter: false }, 
			7: { sorter: false },
        } 
	})
	
	$(".header").append('<span class="ui-icon ui-icon-carat-2-n-s"></span>');

	$('.tooltip').tooltip({
			track: true,
			delay: 0,
			showURL: false,
			showBody: " - ",
			fade: 250
	});

	var no = '<?= $this->t->_('Close'); ?>';
	var title = '<?= $this->t->_('Viewing Log Details'); ?>';

	$('.showUserAgentDialog').bind('click', function() {
		lnk_showDetails(no, $(this).attr('rel'), '/admin/logs/show-detail', 'userAgent', title);
	});

	$('.showInfoDialog').bind('click', function() {
		lnk_showDetails(no, $(this).attr('rel'), '/admin/logs/show-detail', 'info', title);
	});

	$('.deleteSelected').bind('click', function() {
		btn_deleteselected('<?= $this->t->_('Yes'); ?>', '<?= $this->t->_('No'); ?>', 'log-', 'admin/logs/delete/mode/log', '<?= $this->t->_('Success Message'); ?>', '<?= $this->t->_('Items Deleted')?>');
		return false; 
	});

	$('body').removeClass('layout980');
	$('body').addClass('layout1280');

	$('.deleteSelected').addClass('ui-state-disabled');		
});
</script>

<?= $this->partial('_js.phtml'); ?>

<?= $this->partial('_breadcrumbs.phtml', array('breadcrumb' => $this->breadcrumb())); ?>

<div id="page-layout" class="fixed">
	<div id="page-content">
		<div id="page-content-wrapper">
			<div class="inner-page-title">
				<h2><?= $this->t->_('Logs'); ?></h2>
				<span><?= $this->t->_('Here you can view general logged activities'); ?></span>
			</div>
			<div class="hastable">
					<form action="" method="post" class="pager-form" name="myform">
						<table id="sort-table"> 
							<thead> 
								<tr>
									<th style="width:23px">
										<input type="checkbox" class="submit checkbox" onclick="check(this.form.list, '<?= $this->t->_('All Selected'); ?>', '<?= $this->t->_('Select All'); ?>')" value="">
									</th>
								    <th style="width:120px" class="header"><?= $this->t->_('Date of Action'); ?></th>
								    <th class="header"><?= $this->t->_('User ID'); ?></th>  
								    <th class="header"><?= $this->t->_('Referrer'); ?></th> 
								    <th style="width:120px"><?= $this->t->_('Message'); ?></th>
								    <th style="width:210px"><?= $this->t->_('Url'); ?></th>
								    <th><?= $this->t->_('User Agent'); ?></th>
								    <th><?= $this->t->_('Info'); ?></th>
								</tr> 
							</thead> 
						<tbody>
						<?php 
							if (count($this->logs)) :
								$i = 0;
								foreach($this->logs as $log) :	
						?>
							<tr id="log-<?= $log->id; ?>" class="<?php ($i % 2 == 0) ? 'even' : 'odd'; ?>">
								<td><input type="checkbox" value="<?= $log->id; ?>" name="list" class="checkbox checkOne"/></td>
								<td class="center"><?= $this->dateFormat($log->dateInserted, Zend_Date::DATETIME) ?></td> 
							    <td><?= $this->escape($this->userInfo[$log->userId]); ?></td> 
							    <td><?= $this->escape($log->referrer); ?></td> 
							    <td><?= $this->escape($log->message); ?></td> 
							    <td><?= $this->escape($log->url); ?></td> 
							    <td><a class="showUserAgentDialog" rel="<?= $log->id; ?>" href="javascript:void(0);"><?= $this->t->_('View'); ?></a></td>
								<td><a class="showInfoDialog" rel="<?= $log->id; ?>" href="javascript:void(0);"><?= $this->t->_('View'); ?></a></td> 
							</tr>
						<?php 
							    $i++;
								endforeach;
							endif;
						?>						
						</tbody>
						</table>
					
					<div class="clear"></div>
					
					<p>
	                    <button class="ui-state-default float-right ui-corner-all ui-button deleteSelected"><?= $this->t->_('Delete'); ?></button>
					    <button class="ui-state-default float-right ui-corner-all ui-button selectAll" onclick="check(this.form.list, '<?= $this->t->_('All Selected'); ?>', '<?= $this->t->_('Select All'); ?>'); return false;" > <?= $this->t->_('Select All'); ?></button>
	                </p>
	                
					</form>
					<?= $this->paginationControl($this->logs, 'Sliding', '_paginator.phtml'); ?>
					
				</div>
			
			<?= $this->partial('layout-sidebar.phtml', array('section' => 'logs', 't' => $this->t, 'refreshLink' => $this->adminUrl(null, 'logs'))); ?>	
					
	<div class="clear"></div>			
			</div>
		<div class="clear"></div>
	</div>
	</div>
	<div class="clear"></div>