<?= 
	$this->partial('_modals.phtml', 
		array('t' 		  => $this->t,					  
			  'headline'  => 'Edit Workout',
			  'content'   => $this->form
	)); 
?>

<script>
$(document).ready(function(){
	$('.btn-primary').bind('click', function() {
		$('#<?= $this->form->getId(); ?>').submit();
	});
	
	var options = {  
		url: '<?= $this->form->getAction(); ?>',
        success: vkNgineAjaxFormSubmit,
		dataType : 'json'
    };
	   
	$('#<?= $this->form->getId(); ?>').ajaxForm(options);	

	$('.date-picker').datepicker({
		format: 'yyyy-mm-dd'	
	});
});
</script>