<?= $this->partial('_modals.phtml', 
				array('t' 		  => $this->t,					  
					  'headline'  => 'Edit Measurements ',
					  'content'   => $this->form
	)); 
?>

<script>
$(document).ready(function(){
	var options = {  
		url: '<?= $this->form->getAction(); ?>',
        success: vkNgineAjaxFormSubmit,
		dataType : 'json'
    };
    
	$('#<?= $this->form->getId(); ?>').ajaxForm(options);

	$('.datePicker').datepicker({
		changeMonth: true,
		changeYear: true,
		showButtonPanel: true,
		dateFormat: 'yy-mm-dd'
	});
});
</script>