<?= $this->form; ?>

<script>
$(document).ready(function(){
	$("#name").focus();

	$('select').select_skin();

	var options = {  
		url: '<?= $this->form->getAction(); ?>',
        success: vkNgineAjaxFormSubmit,
		dataType : 'json'
    };
    
	$('#<?= $this->form->getId(); ?>').ajaxForm(options);

	$('.datePicker').datepicker({
		changeMonth: true,
		changeYear: true,
		showButtonPanel: true,
		dateFormat: 'yy-mm-dd'
	});
});
</script>