<?= $this->partial('_breadcrumbs.phtml', 
		array('t' 		  => $this->t,
			  'pageTitle' => $this->t->_($this->user->getFullname()),
			  'page'	  => $this->t->_('My Settings'),
	)); 
?>

<?php
	$this->headScript()
		 	->appendFile($this->baseUrl('/js/public/vkNgine.myaccount.js'))
		 	->appendFile($this->baseUrl('/js/public/vkNgine.myaccount.modals.js'));		 	
?>     

               <div class="row-fluid">
                  <div class="span12"> 
                  	  <div class="portlet box blue">       
                  	  	<div class="portlet-title">
                  	  		<div class="caption">
								<i class="icon-reorder"></i>
								<span class="hidden-480"><?= $this->t->_('Change Password'); ?></span>
							</div>
						</div>
                        <div class="portlet-body form">
                           <form action="<?= $this->formSettings->getAction(); ?>" class="horizontal-form">
                               <div class="row-fluid">
                               	   <div class="span6 ">
		                              <div class="control-group">
		                                 	<div class="controls">
		                                 		<?= $this->formSettings->password; ?>
		                                 	</div> 
		                              </div>
		                           </div>
		                       </div>            
                           </form>
                       </div>
                     </div>  
                     <div class="portlet box blue">  
                     	<div class="portlet-title">
                  	  		<div class="caption">
								<i class="icon-reorder"></i>
								<span class="hidden-480"><?= $this->t->_('Default Calendar View'); ?></span>
			</div>
		</div>
		<div class="portlet-body form">
		   <form action="<?= $this->formSettings->getAction(); ?>" class="horizontal-form">
                              <div class="row-fluid">
                               	   <div class="span6 ">
		                              <div class="control-group">
		                              	  <div class="controls">
                                    		 <?= $this->formSettings->calendarView; ?>
                                 		  </div>
                                      </div>
                                   </div>
                              </div>            
                           </form>
                        </div>
                     </div>   
                     
                     <div class="portlet box blue">  
                     	<div class="portlet-title">
                  	  		<div class="caption">
								<i class="icon-reorder"></i>
								<span class="hidden-480"><?= $this->t->_('Notifications'); ?></span>
							</div>
						</div>
						<div class="portlet-body form">
                           <form action="<?= $this->formSettings->getAction(); ?>" class="horizontal-form">
                           	     <div class="row-fluid">
                               	   <div class="span6 ">
		                              <div class="control-group">
		                              	  <div class="controls">
		                              	  		<?= $this->formSettings->notifications; ?>
                                    	  </div>
                                      </div>
                                 	</div>
                                 </div>                               
                           </form>
                        </div>
                     </div>
                     
                     <div class="portlet box blue">  
                     	<div class="portlet-title">
                  	  		<div class="caption">
								<i class="icon-reorder"></i>
								<span class="hidden-480"><?= $this->t->_('Language'); ?></span>
			</div>
		</div>
		<div class="portlet-body form">
			<p align="center">
		   	  <a class="language" data-lang="tr"><img src="/images/Turkey.png" width="32"></a>
			  <a class="language" data-lang="en"><img src="/images/Us.png" width="32"></a>
		   </p>
		   <p class="warning">
		   	  <?= $this->t->_('Clicking a flag will change the language for the current session'); ?>
						   </p>
						</div>	
				 	</div>       
                  
               </div>
			</div>
			
<script type="text/javascript">
	var core = new vkNgine.core.engine();
	core.initMyAccount();
</script>