<?= $this->partial('_breadcrumbs.phtml', 
				array('t' 		  => $this->t,
					  'pageTitle' => $this->t->_($this->user->getFullname()),
					  'page'	  => $this->t->_('My Settings'),
						
	)); 
?>
               <div class="row-fluid">
                  <div class="span12"> 
                  	  <div class="portlet box blue">       
                  	  	<div class="portlet-title">
                  	  		<div class="caption">
								<i class="icon-reorder"></i>
								<span class="hidden-480"><?= $this->t->_('Change Password'); ?></span>
							</div>
						</div>
                        <div class="portlet-body form">
                           <form action="<?= $this->formSettings->getAction(); ?>" class="horizontal-form">
                               <div class="row-fluid">
                               	   <div class="span6 ">
		                              <div class="control-group">
		                                 	<div class="controls">
		                                 		<?= $this->formSettings->password; ?>
		                                 	</div> 
		                              </div>
		                           </div>
		                       </div>            
                           </form>
                       </div>
                     </div>  
                     <div class="portlet box blue">  
                     	<div class="portlet-title">
                  	  		<div class="caption">
								<i class="icon-reorder"></i>
								<span class="hidden-480"><?= $this->t->_('Default Calendar View'); ?></span>
							</div>
						</div>
						<div class="portlet-body form">
						   <form action="<?= $this->formSettings->getAction(); ?>" class="horizontal-form">
                              <div class="row-fluid">
                               	   <div class="span6 ">
		                              <div class="control-group">
		                              	  <div class="controls">
                                    		 <?= $this->formSettings->calendarView; ?>
                                 		  </div>
                                      </div>
                                   </div>
                              </div>            
                           </form>
                        </div>
                     </div>   
                     
                     <div class="portlet box blue">  
                     	<div class="portlet-title">
                  	  		<div class="caption">
								<i class="icon-reorder"></i>
								<span class="hidden-480"><?= $this->t->_('Notifications'); ?></span>
							</div>
						</div>
						<div class="portlet-body form">
                           <form action="<?= $this->formSettings->getAction(); ?>" class="horizontal-form">
                           	     <div class="row-fluid">
                               	   <div class="span6 ">
		                              <div class="control-group">
		                              	  <div class="controls">
		                              	  		<?= $this->formSettings->notifications; ?>
                                    	  </div>
                                      </div>
                                 	</div>
                                 </div>                               
                           </form>
                        </div>
                     </div>
                     
                     <div class="portlet box blue">  
                     	<div class="portlet-title">
                  	  		<div class="caption">
								<i class="icon-reorder"></i>
								<span class="hidden-480"><?= $this->t->_('Language'); ?></span>
							</div>
						</div>
						<div class="portlet-body form">
							<p align="center">
						   	  <a class="language" href="javascript:void(0);" rel="tr"><img src="/images/Turkey.png" width="32"></a>
							  <a class="language" href="javascript:void(0);" rel="en"><img src="/images/Us.png" width="32"></a>
						   </p>
						   <p class="warning">
						   	  <?= $this->t->_('Clicking a flag will change the language for the current session'); ?>
						   </p>
						</div>	
				 	</div>       
                  
               </div>
			</div>
			
<script>
$('.description').addClass('warning');

$('.setCalendarView').change(function(){
	var selected = $(".setCalendarView option:selected");    
	if(selected.val()){
		$.ajax( {
			url: '/my-account/index/method/1/calendarview/1/value/' + selected.val(),
			dataType : 'json',
			
			success: function(data) {
				$.gritter.add({
					title: data.title,
					text: data.message,
					image: '/images/admin/icons/success.png',
					sticky: false,
					time: 3000
				});
			}
		});
	}
});

$(".input-password").change(function(){
	$.ajax( {
		url: '/my-account/index/method/1/password/1/',
		dataType : 'json',
		type: 'POST',
		data: { password: $(this).val() },
		success: function(data) {
			var icon = data.icon ? data.icon : 'success';
			$.gritter.add({
				title: data.title,
				text: data.message,
				image: '/images/admin/icons/' + icon + '.png',
				sticky: false,
				time: 3000
			});
		}
	});
});

$("input[name='notifications']").change(function(){
	$.ajax( {
			url: '/my-account/index/method/get/notifications/1/value/' + $(this).val(),
			dataType : 'json',
			success: function(data) {
				$.gritter.add({
					title: data.title,
					text: data.message,
					image: '/images/admin/icons/success.png',
					sticky: false,
					time: 3000
				});
			}
		});
});

$('.language').bind('click', function() {
	var lang = $(this).attr('rel');
	
	$.ajax( {
		url: '/my-account/language/lang/' + lang,
		dataType : 'json',
		success: function(data) {
			if(data.success)
				window.top.location = '/';
		}
	});
	return false;
}); 
</script>