<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
	<h3><?= $this->t->_($this->workout['name']); ?></h3>
</div>
<div class="modal-body">	
	<div class="accordion" id="days">	
		<?php for($i=1; $i<=$this->workout['day']; $i++) : ?>
        <div class="accordion-group">		
        	<div class="accordion-heading">
                 <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#days" href="#day_<?= $i; ?>">
                 	<i class="icon-chevron-left"></i>
                 		<?= $this->t->_('Day'); ?> <?= $i; ?>
                 </a>
            </div>            
            <div id="day_<?= $i; ?>" class="accordion-body collapse">
            	<div class="accordion-inner">
            		<?php
            			$exercises = $this->exercises->fetchAllPerDay($this->workout['workoutId'], $i);  
            			if(count($exercises) > 0) :
            		?>
            			<table class="table table-condensed table-hover">
            			  <thead>
                              <tr>
                                 <th style="width:150px;"><?= $this->t->_('Exercise'); ?></th>
                                 <th style="width:50px;"><?= $this->t->_('Sets'); ?></th>
                                 <th style="width:50px;"><?= $this->t->_('Reps'); ?></th>
                                 <th style="width:50px;"><?= $this->t->_('Order'); ?></th>
                                 <th style="width:50px;"></th>
                              </tr>
                           </thead>
					<?php foreach($exercises as $exercise) : ?>
							<tbody>
                              <tr>
                                 <td>
                                    <a href="javascript:void(0);" data-id="<?= $exercise['exerciseId']; ?>" data-target="exercisedetail" class="vkNgine-modal">
										<?= $this->exerciseDetail[$exercise['exerciseId']]; ?>
									</a>
                                 </td>
                                 <td>
			 						 <input id="sets" class="input-mini setField" data-id="<?= $exercise['id']; ?>" style="width:20px;" data-field="sets" type="text" value="<?= $exercise['sets']; ?>" placeholder="<?= $this->t->_('Sets'); ?>" >
                                 </td>
                                 <td>
								     <input id="reps" class="input-mini setField" data-id="<?= $exercise['id']; ?>" style="width:20px;" data-field="reps" type="text" value="<?= $exercise['reps']; ?>" placeholder="<?= $this->t->_('Reps'); ?>" >
								 </td>
								 <td>
								 	<input id="order" class="input-mini setField" data-id="<?= $exercise['id']; ?>" style="width:20px;" data-field="order" type="text" value="<?= $exercise['order']; ?>" placeholder="<?= $this->t->_('Order'); ?>" >
								 </td>
								 <td>	
									<span id="set-saved-<?= $exercise['id']; ?>"></span>
									<span id="rep-saved-<?= $exercise['id']; ?>"></span>
									<span id="order-saved-<?= $exercise['id']; ?>"></span>										 	
								 </td>
                              </tr>	
							</tbody>						
					<?php endforeach; ?>
					<?php else: ?>
						<small><?= $this->t->_('No Exercises added yet, go to Exercises list and add an exercise to this workout and day'); ?></small>
					<?php endif; ?>
					</table>
                </div>
            </div>
        </div>				
		<?php endfor; ?>        
	</div>
</div>
<div class="modal-footer">
	<button class="btn" data-dismiss="modal" type="button"><?= $this->t->_('Close'); ?></button>
</div>

<script type="text/javascript">		
	var setsaved = '<?= $this->t->_('Set saved'); ?>';
	var repsaved = '<?= $this->t->_('Rep saved'); ?>';
	var ordersaved = '<?= $this->t->_('Order saved'); ?>';

	UIModals.init();
	UIModals.myAccount('manage-workout', setsaved, repsaved, ordersaved);
</script>