<?= 
	$this->partial('_breadcrumbs.phtml', 
		array('t' 		  => $this->t,		
			  'pageTitle' => $this->t->_('My Body Measurements'), 
			  'page'	  => $this->t->_('My Body Measurements'),
	)); 
?>


<div class="row-fluid">
		<div class="span12">			
			<div class="portlet box blue">
				<div class="portlet-title">
                  	<div class="caption">
						<i class="icon-reorder"></i>
						<span class="hidden-480"><?= $this->t->_('My Measurements'); ?></span>
					</div>                       							
				</div>	
				<div class="portlet-body">
					<table class="table table-striped table-hover">
						<thead>
							<tr>
								<th><?= $this->t->_('Value'); ?></th>
						        <th><?= $this->t->_('Type'); ?></th>
						        <th><?= $this->t->_('Record Date'); ?></th>
						        <th><?= $this->t->_('Actions'); ?></th>
							</tr>
						</thead>
						<tbody>
							<?php
								foreach($this->measurements as $measurements) :
							?>	
						      <tr>
						        <td><?= $this->escape($measurements['value']); ?></td>
						        <td><?= ($measurements['type'] == 'WEIGHT') ? $this->t->_('Weight') : $this->t->_('Not Entered'); ?></td>
						        <td><?= $this->escape($this->dateFormat($measurements['date'], Zend_Date::DATE_FULL)); ?></td>
						        <td>
						          <a href="#deletemeasurement_dialog" class="glyphicons bin deletemeasurement" rel="<?= $measurements['id']; ?>" data-toggle="modal">
						          	<i class="icon-remove"></i> <?= $this->t->_('Delete'); ?>
						          </a>
						        </td>						        
						      </tr>
						    <?php 
								endforeach;
							?>		
						</tbody>
					</table>
					<div>
						<a class="btn blue editmeasurements" data-toggle="modal" href="#editmeasurements_dialog"><i class="icon-plus"></i> <?= $this->t->_('Add New Measurement'); ?></a>
				    </div>
				    				      
				</div>
			</div>			
		</div>
	</div>

<script>
$('.editmeasurements').bind('click', function() {
	btn_editmeasurements($(this).attr('rel'));
});

$('.deletemeasurement').bind('click', function() {
	btn_deletemeasurement($(this).attr('rel'));
});
</script>