<?= $this->partial('_breadcrumbs.phtml', 
				array('t' 		  => $this->t,
					  'pageTitle' => null,
					  'page'	  => $this->t->_('My Body Measurements'),
	)); 
?>

<div id="page" class="dashboard">
	<div class="row-fluid">
		<div class="span12">			
			<div class="widget">
				<div class="widget-title">
					<h4><i class="icon-table"></i> <?= $this->t->_('My Body Measurements'); ?></h4>										
				</div>
				<div class="widget-body">
					<table class="table table-striped table-bordered" id="sample_1">
						<thead>
							<tr>
						        <th><?= $this->t->_('Value'); ?></th>
						        <th><?= $this->t->_('Type'); ?></th>
						        <th><?= $this->t->_('Record Date'); ?></th>
						        <th><?= $this->t->_('Actions'); ?></th>
						     </tr>
						</thead>
						<tbody>
						
							<?php
								foreach($this->measurements as $measurements) :
							?>	
						      <tr class="odd gradeX">
						        <td><?= $this->escape($measurements['value']); ?></td>
						        <td><?= ($measurements['type'] == 'WEIGHT') ? $this->t->_('Weight') : $this->t->_('Not Entered'); ?></td>
						        <td><?= $this->escape($this->dateFormat($measurements['date'], Zend_Date::DATE_FULL)); ?></td>
						        <td>
						          <a href="javascript:void(0);" class="icon huge deletemeasurement" rel="<?= $measurements['id']; ?>">
						          	<i class="icon-remove"></i> <?= $this->t->_('Delete'); ?>
						          </a>
						        </td>						        
						      </tr>
						    <?php 
								endforeach;
							?>
							
						</tbody>
					</table>
					<div>
						<a class="editmeasurements" href="#">							
							<?= $this->t->_('Add New Measurement');?>
						</a>
				      </div>
				</div>
			</div>			
		</div>
	</div>
</div>

<script>
$('.editmeasurements').bind('click', function() {
	var id = $(this).attr('rel');
	btn_editmeasurements('<?= $this->t->_('Save'); ?>', '<?= $this->t->_('Cancel'); ?>', id);
});

$('.deletemeasurement').bind('click', function() {
	var id = $(this).attr('rel');
	btn_deletemeasurement('<?= $this->t->_('Delete'); ?>', '<?= $this->t->_('Cancel'); ?>', id);
});
</script>