<?php 
	$language = new Zend_Session_Namespace('language');
   	if('tr' == vkNgine_Config::getSystemConfig()->language->locale || 'tr' == $language->lang) {	 
   		$pageTitle = date('j ') . ' ' . $this->t->_(date('F')) . ' ' . date(' Y');
   	}
   	else {
   		$pageTitle = date('F j, Y');
   	}
?>
		    
<?= 
	$this->partial('_breadcrumbs.phtml', 
		array('t' 		  => $this->t,					 
			  'page'	  => $this->t->_('My Plate'),
	)); 
?>

			<div id="page">
               <div class="row-fluid">
                  <div class="span12">                     
                     <div class="widget">
                        <div class="widget-title">
                           <h4><i class="icon-food"></i> <?= $this->t->_('My Plate') . ' :: ' . $pageTitle; ?></h4>                           							
                        </div>
                        <div class="widget-body form">
                        
                           <h5><?= $this->t->_('My Meals'); ?></h5>
                           
                           <form action="<?= $this->formMeals->getAction(); ?>" class="form-inline">
                              <div class="control-group">
                                 <div class="controls">
                                    <?= $this->formMeals; ?>
							        <button class="btn btn-inverse addmeal">
										<i class="icon-plus icon-white"></i> <?= $this->t->_('Add Meal'); ?>
									</button>								        
                                 </div>
                              </div>            
                           </form>
                           
                           <h5><?= $this->t->_('Foods'); ?></h5>
                           
                           <form action="<?= $this->formFoods->getAction(); ?>" class="form-inline">
                                 <div class="controls">
                                    <?= $this->formFoods->foodId; ?>
                                    <?= $this->formFoods->foodSearch; ?>
                                    <div id="servingSize" style="padding-top:10px;padding-left:3px"><?= $this->t->_('Serving Size'); ?>: <span id="servingSizeValue"></span></div>
                                 </div>                               
                                 <div class="controls">
                                 	<?= $this->formFoods->servingSize; ?>
  									<?= $this->formFoods->servingSizes; ?>
                                 </div>                                 
							     <button class="btn btn-inverse addfood">
										<i class="icon-plus icon-white"></i> <?= $this->t->_('Add Food'); ?>
	 							 </button>
                           </form>
                           
                        </div>
                     </div>                     
                  </div>
               </div>
			</div>	
			 
    <?php 
    	if('tr' == vkNgine_Config::getSystemConfig()->language->locale || 'tr' == $language->lang) {	 
    		$date = date('j ') . ' ' . $this->t->_(date('F')) . ' ' . date(' Y');
    	}
    	else {
    		$date =  date('F j, Y');
    	}
?>

<div class="row-fluid">
	<div class="span12">		
		<div class="widget">
			<div class="widget-title">
				<h4><i class="icon-food"></i> <?= $this->t->_('Foods'); ?> :: <?= $this->t->_('Summary of Daily Consumption'); ?> :: <?= $date; ?></h4>								
			</div>
			<div class="widget-body">
				<table id="dailyFoods" class="table table-condensed table-hover">
				<thead>
					<tr>
						<th><?= $this->t->_('Name'); ?></th>
		      			<th><?= $this->t->_('Serving'); ?></th>
		      			<th><?= $this->t->_('Calories'); ?></th>
		      			<th><?= $this->t->_('Fat'); ?></th>
		      			<th><?= $this->t->_('Cholesterol'); ?></th>
		      			<th><?= $this->t->_('Sodium'); ?></th>
		      			<th><?= $this->t->_('Carbs'); ?></th>
		      			<th><?= $this->t->_('Fiber'); ?></th>
		      			<th><?= $this->t->_('Protein'); ?></th>
		      			<th><?= $this->t->_('Sugar'); ?></th>
					</tr>
				</thead>	
	      		<tbody>
	      			<?php 
	      			$totals = 0;
			      	    foreach($this->dailyIntake as $intake):
			      	    	if($intake['mealId']):
			      	  			$modelMeals = new Model_Meals();
							    $meal = $modelMeals->fetchMealTotal($intake['mealId']);
							    
							    $modelMealsFoods = new Model_Meals_Foods();
							    $foods = $modelMealsFoods->fetchAll('mealId = ' . $intake['mealId']);
							    
					  ?>
					<tr class="sum">
		      			<td><?= $meal['title']; ?></td>
		      	  		<td>
		      	  			<?php 
		      	  				foreach($foods as $food) {
		      	  					$foodDetail = $this->modelFoods->fetch($food['foodId']);
		      	  					
		      	  					echo $foodDetail->getName() . ' x ' . $foodDetail['servingSize'] . '  <br> ';
		      	  				}
		      	  		    ?>
		      	  		</td>
		      	  		<td data-calories="<?= $meal['calories']; ?>">
		      	  			<?= $meal['calories']; ?>
		      	  		</td>
		      	  		<td data-fat="<?= $meal['fat']; ?>">
		      	  			<?= $meal['fat']; ?>
		      	  		</td>
		      	  		<td data-cholesterol="<?= $meal['cholesterol']; ?>">
		      	  			<?= $meal['cholesterol']; ?>
		      	  		</td>
		      	  		<td data-sodium="<?= $meal['sodium']; ?>">
		      	  			<?= $meal['sodium']; ?>
		      	  		</td>
		      	  		<td data-carbs="<?= $meal['carbs']; ?>">
		      	  			<?= $meal['carbs']; ?>
		      	  		</td>
		      	  		<td data-fiber="<?= $meal['fiber']; ?>">
		      	  			<?= $meal['fiber']; ?>
		      	  		</td>
		      	  		<td data-protein="<?= $meal['protein']; ?>">
		      	  			<?= $meal['protein']; ?>
		      	  		</td>
		      	  		<td data-sugar="<?= $meal['sugar']; ?>">
		      	  			<?= $meal['sugar']; ?>
		      	  		</td>
		      		</tr>
		      				
		      		<?php 	      	  			
		      	  		else:
		      	  			$food = $this->modelFoods->fetch($intake['foodId'])->toArray();
		      	    ?>
		      	    			
		      	    <tr class="sum">
		      			<td><?= $food['name']; ?></td>
		      	  		<td><?= $intake['servingSize']; ?> <?= $this->t->_($food['servingSizeType']); ?></td>
		      	  		<td data-calories="<?= $this->modelFoods->calculateMacros($food['calories'], $food['servingSize'], $intake['servingSize'], 0); ?>">
		      	  			<?= $this->modelFoods->calculateMacros($food['calories'], $food['servingSize'], $intake['servingSize'], 'N/A'); ?>
		      	  		</td>
		      			<td data-fat="<?= $this->modelFoods->calculateMacros($food['fat'], $food['servingSize'], $intake['servingSize'], 0); ?>">
		      				<?= $this->modelFoods->calculateMacros($food['fat'], $food['servingSize'], $intake['servingSize'], 'N/A'); ?>
		      			</td>
		      			<td data-cholesterol="<?= $this->modelFoods->calculateMacros($food['cholesterol'], $food['servingSize'], $intake['servingSize'], 0); ?>">
		      				<?= $this->modelFoods->calculateMacros($food['cholesterol'], $food['servingSize'], $intake['servingSize'], 'N/A'); ?>
		      			</td>
		      			<td data-sodium="<?= $this->modelFoods->calculateMacros($food['sodium'], $food['servingSize'], $intake['servingSize'], 0); ?>">
		      				<?= $this->modelFoods->calculateMacros($food['sodium'], $food['servingSize'], $intake['servingSize'], 'N/A'); ?>
		      			</td>
		      			<td data-carbs="<?= $this->modelFoods->calculateMacros($food['carbs'], $food['servingSize'], $intake['servingSize'], 0); ?>">
		      				<?= $this->modelFoods->calculateMacros($food['carbs'], $food['servingSize'], $intake['servingSize'], 'N/A'); ?>
		      			</td>
		      			<td data-fiber="<?= $this->modelFoods->calculateMacros($food['fiber'], $food['servingSize'], $intake['servingSize'], 0); ?>">
		      				<?= $this->modelFoods->calculateMacros($food['fiber'], $food['servingSize'], $intake['servingSize'], 'N/A'); ?>
		      			</td>
		      			<td data-protein="<?= $this->modelFoods->calculateMacros($food['protein'], $food['servingSize'], $intake['servingSize'], 0); ?>">
		      				<?= $this->modelFoods->calculateMacros($food['protein'], $food['servingSize'], $intake['servingSize'], 'N/A'); ?>
		      			</td>
		      			<td data-sugar="<?= $this->modelFoods->calculateMacros($food['sugar'], $food['servingSize'], $intake['servingSize'], 0); ?>">
		      				<?= $this->modelFoods->calculateMacros($food['sugar'], $food['servingSize'], $intake['servingSize'], 'N/A'); ?>
		      			</td>
		      		</tr>
		      	   <?php 
		      	  	 	 endif;
		      		 endforeach; 
		      	   ?>
		      	   <tr id="totals">
			      		<td><span style="float:right"><?= $this->t->_('Total'); ?></span></td>
		      	  		<td></td>
		      	  		<td class="total-calories"></td>
		      	  		<td class="total-fat"></td>
		      	  		<td class="total-cholesterol"></td>
		      	  		<td class="total-sodium"></td>
		      	  		<td class="total-carbs"></td>
		      	  		<td class="total-fiber"></td>
		      	  		<td class="total-protein"></td>
		      	  		<td class="total-sugar"></td>
		      	   </tr>
				</tbody>
			</table>
			</div>
		</div>		
	</div>	
</div>

<script type="text/javascript">
	var total = function() {
		var macros = new Array("calories","fat","cholesterol","sodium","carbs","fiber","protein","sugar");

		for(var i=0; i<macros.length; i++) {
			var macroValue = 0;

			$('.sum').each(function() {
				macroValue += parseFloat($(this).find('td').eq(i+2).data(macros[i]));				
		    });
		    
		    $('.total-' + macros[i] + '').text(macroValue);
		}	
	};
	total();	
  
 	var options = {
		script:"/my-account/my-plate?food=1&",
		varname:"foodsearch",
		json:true,
		shownoresults:true,
		maxresults:100,
		maxentries:100,
		delay:1,
		callback: function (obj) { 
			$('#foodId').val(obj.id);  
			$('#servingSizeValue').html(obj.servingSize);		
			$("#servingSizes option[value=" + obj.servingSizeType + "]").attr('selected', 'selected');			
		}
	};
	var as_json = new bsn.AutoSuggest('foodSearch', options);
</script>

<script>
$(function() {
	var date = '<?= date('Y-m-d'); ?>';
	
	$('.addmeal').bind('click', function(e) {
		e.preventDefault();
		var mealId = $('#meals').val();
		
		$.ajax( {
	        url: '/my-account/my-plate/mealId/' + mealId + '/date/' + date,
	        dataType : 'json',
	        success: function(data) { 
		        if(data.success) {
		        	window.top.location = '/my-account/my-plate';
		        }		        
			}
	   });
	});

	$('.addfood').bind('click', function(e) {
		e.preventDefault();
		var foodId = $('#foodId').val();
		var servingSize = $('#servingSize').val();
		var servingSizes = $('#servingSizes').val();
		
		if(!foodId || !servingSize || !servingSizes) {
			alert('Please enter a food, how much of it consumed, and consumed serving size.');
			return false;
		}

		$.ajax( {
	        url: '/my-account/my-plate/foodIds/' + foodId + '/servingSize/' + servingSize + '/servingSizes/' + servingSizes + '/date/' + date,
	        dataType : 'json',
	        success: function(data) { 
		        if(data.success){
		        	window.top.location = '/my-account/my-plate';
		        }
			}
	       }
	    );
	});
});
</script>