<?= 
	$this->partial('_breadcrumbs.phtml', 
		array('t' 		  => $this->t,		
			  'pageTitle' => $this->t->_('My Workouts'),				 
			  'page'	  => $this->t->_('My Workouts'),
	)); 
?>

<?php
	$this->headScript()
		 	->appendFile($this->baseUrl('/js/public/vkNgine.myaccount.js'))
		 	->appendFile($this->baseUrl('/js/public/vkNgine.myaccount.modals.js'));		 	
?>

	<div class="row-fluid">
		<div class="span12">			
			<div class="portlet box blue">
				<div class="portlet-title">
                	<div class="caption">
						<i class="icon-reorder"></i>
						<span class="hidden-480"><?= $this->t->_('My Workouts'); ?></span>
				</div>
			</div>	
			<div class="portlet-body">
				<table class="table table-striped table-hover">
					<thead>
						<tr>
							<th><?= $this->t->_('Workout Name'); ?></th>
					        <th><?= $this->t->_('Days'); ?></th>
					        <th><?= $this->t->_('Start Date'); ?></th>
					        <th><?= $this->t->_('End Date'); ?></th>
					        <th style="text-align:right"><?= $this->t->_('Actions'); ?></th>
						</tr>
					</thead>
					<tbody>
						<?php
							foreach($this->workouts as $workout) :
						?>	
					      <tr class="odd gradeX">
					        <td><a href="<?= $this->publicUrl('view-workout', 'my-account'); ?>/id/<?= $workout['workoutId']; ?>"><?= $this->escape($workout['name']); ?></a></td>
					        <td><?= $this->escape($workout['day']); ?></td>
					        <td><?= ($workout['startDate'] != '0000-00-00') ? $this->escape($this->dateFormat($workout['startDate'], Zend_Date::DATE_FULL)) : $this->t->_('Not entered') ?></td>
					        <td><?= ($workout['endDate'] != '0000-00-00') ? $this->escape($this->dateFormat($workout['endDate'], Zend_Date::DATE_FULL)) : $this->t->_('Not entered') ?></td>
					        <td style="text-align:right">
								<a class="glyphicons more_items vkNgine-modal" data-id="<?= $workout['workoutId']; ?>" data-target="manageworkout">
									<i></i>
									<?= $this->t->_('Manage'); ?>
								</a> 	
								<a class="glyphicons edit vkNgine-modal" data-id="<?= $workout['workoutId']; ?>" data-target="editworkout">
									<i></i>
									<?= $this->t->_('Edit'); ?>
								</a> 
								<a class="glyphicons bin vkNgine-modal" data-id="<?= $workout['workoutId']; ?>" data-target="deleteworkout">
									<i></i>
									<?= $this->t->_('Delete'); ?>
								</a> 		
							</td>						        
					      </tr>
					    <?php 
							endforeach;
						?>
						
					</tbody>
				</table>
				<div>
					<a class="btn blue vkNgine-modal" data-target="editworkout"><i class="icon-plus"></i> <?= $this->t->_('Add New Workout'); ?></a>
			    </div>				    
			</div>
		</div>			
	</div>
</div>

<script>
	vkNgineModals.myAccount();
</script>