<?= $this->partial('_breadcrumbs.phtml', 
				array('t' 		  => $this->t,
					  'pageTitle' => null,
					  'page'	  => $this->t->_('My Workouts'),
	)); 
?>

<div id="page" class="dashboard">
	<div class="row-fluid">
		<div class="span12">
			
			<div class="widget">
				<div class="widget-title">
					<h4><i class="icon-table"></i> <?= $this->t->_('My Workouts'); ?></h4>
					<span class="tools">
					<a href="javascript:;" class="icon-chevron-down"></a>
					<a href="#widget-config" data-toggle="modal" class="icon-wrench"></a>
					<a href="javascript:;" class="icon-refresh"></a>		
					<a href="javascript:;" class="icon-remove"></a>
					</span>							
				</div>
				<div class="widget-body">
					<table class="table table-striped table-bordered" id="sample_1">
						<thead>
							<tr>
								<th><?= $this->t->_('Workout Name'); ?></th>
						        <th><?= $this->t->_('Days'); ?></th>
						        <th><?= $this->t->_('Start Date'); ?></th>
						        <th><?= $this->t->_('End Date'); ?></th>
						        <th><?= $this->t->_('Actions'); ?></th>
							</tr>
						</thead>
						<tbody>
							<?php
								foreach($this->workouts as $workout) :
							?>	
						      <tr class="odd gradeX">
						        <td><a href="<?= $this->publicUrl('view-workout', 'my-account'); ?>/id/<?= $workout['workoutId']; ?>"><?= $this->escape($workout['name']); ?></a></td>
						        <td><?= $this->escape($workout['day']); ?></td>
						        <td><?= ($workout['startDate'] != '0000-00-00') ? $this->escape($this->dateFormat($workout['startDate'], Zend_Date::DATE_FULL)) : $this->t->_('Not entered') ?></td>
						        <td><?= ($workout['endDate'] != '0000-00-00') ? $this->escape($this->dateFormat($workout['endDate'], Zend_Date::DATE_FULL)) : $this->t->_('Not entered') ?></td>
						        <td>
									<a href="javascript:void(0);" class="icon huge manageworkout" rel="<?= $workout['workoutId']; ?>"><i class="icon-cog"></i> <?= $this->t->_('Manage'); ?></a> 	
									<a href="javascript:void(0);" class="icon huge editworkout" rel="<?= $workout['workoutId']; ?>"><i class="icon-pencil"></i> <?= $this->t->_('Edit'); ?></a> 
									<a href="javascript:void(0);" class="icon huge deleteworkout" rel="<?= $workout['workoutId']; ?>"><i class="icon-remove"></i> <?= $this->t->_('Delete'); ?></a> 		
								</td>						        
						      </tr>
						    <?php 
								endforeach;
							?>
							
						</tbody>
					</table>
					<div>
						<a class="editworkout" href="#">							
							<?= $this->t->_('Add New Workout');?>
						</a>
				      </div>
				</div>
			</div>			
		</div>
	</div>
</div>
					
<script>
$('.editworkout').bind('click', function() {
	var id = $(this).attr('rel');
	btn_editworkout('<?= $this->t->_('Save'); ?>', '<?= $this->t->_('Cancel'); ?>', id);
});

$('.manageworkout').bind('click', function() {
	var id = $(this).attr('rel');
	btn_manageworkout('<?= $this->t->_('Close'); ?>', id);
});

$('.deleteworkout').bind('click', function() {
	var id = $(this).attr('rel');
	btn_deleteworkout('<?= $this->t->_('Delete'); ?>', '<?= $this->t->_('Cancel'); ?>', id);
});
</script>