<?= 
	$this->partial('_breadcrumbs.phtml', 
		array('t' 		  => $this->t,
			  'pageTitle' => $this->t->_($this->user->getFullname()),
			  'page'	  => $this->t->_('My Workouts'),
			  'pageHref'  => $this->publicUrl('my-workouts', 'my-account'),
 			  'page2'     => $this->t->_($this->workout['name']),
						
	)); 
?>

<div class="row-fluid">
	<div class="span12">			
		<div class="portlet box blue">
			<div class="portlet-title">
     			<div class="caption">
					<i class="icon-reorder"></i>
					<span class="hidden-480"><?= $this->workout['name']; ?></span>
				</div>                       							
			</div>
			<div class="portlet-body">
				<p class="lead"><?= $this->t->_('Notes'); ?></p>
				<p><?= nl2br($this->t->_($this->workout['notes']));?></p>
				
				<p class="lead"><?= $this->t->_('Workout Details'); ?></p>
		    	<dl>
					<dt><?= $this->t->_('Name'); ?></dt>
					<dd><?= $this->workout['name']; ?></dd>
					<dt><?= $this->t->_('Day'); ?></dt>
					<dd><?= $this->t->_($this->workout['day']); ?></dd>
					<dt><?= $this->t->_('Start Date'); ?></dt>
					<dd><?= $this->t->_($this->workout['startDate']); ?></dd>
					<dt><?= $this->t->_('End Date'); ?></dt>
					<dd><?= $this->t->_($this->workout['endDate']); ?></dd>
					<?php if($this->workout['source']) : ?>	
						<dt><?= $this->t->_('Source');  ?></dt>
						<dd>
							<a href="<?= $this->t->_($this->workout['source']); ?>" target="_blank"><?= $this->t->_('View'); ?></a>
						</dd>
					<?php endif; ?>	
				</dl>
		    	
			</div>
		 </div>
	
		 <div class="portlet box blue">
		 	<div class="portlet-title">
     			<div class="caption">
					<i class="icon-reorder"></i>
					<span class="hidden-480"><?= $this->t->_('Workout Days'); ?></span>
				</div>                       							
			</div>
			<div class="portlet-body">
			<?php
				if(0 != count($this->workoutsExercises->fetchAll('workoutId = ' . $this->workout['workoutId']))) :
					for($i=1; $i<=$this->workout['day']; $i++) :
			?>
					<span class="lead"><?= $this->t->_('Day'); ?> <?= $i?></span>
					<table class="table table-condensed table-hover">
					    <thead>
					       <tr>
					         <th><?= $this->t->_('Exercise Name'); ?></th>
						     <th><?= $this->t->_('Sets'); ?></th>
						     <th><?= $this->t->_('Reps'); ?></th>
					       </tr>
						</thead>
						<tbody>
						<?php foreach($this->workoutsExercises->fetchAllPerDay($this->workout['workoutId'], $i) as $exercise) : ?>
						<tr>
					        <td><a href="<?= $this->publicUrl('view', 'index'); ?>/id/<?= $exercise['exerciseId']; ?>" class="exercisedetail">
									<?= $this->exerciseDetail[$exercise['exerciseId']]; ?>
					   		</a></td>
					        <td><?= $exercise['sets']; ?></td>
					        <td><?= $exercise['reps']; ?></td>
					    </tr>
						<?php endforeach; ?>
					</table>
				
			<?php endfor; ?>
			<?php endif; ?> 
			</div>	
		</div>
	</div>
</div>