<td <?= $this->cssBgColor; ?> data-date=<?= $this->date; ?> data-action="<?= $this->action; ?>" data-target="addexercise" class="<?= $this->class; ?> vkNgine-modal fc-widget-content <?= $this->highlightedCss; ?> <?= $this->firstLast; ?> ">
  <div style="min-height: 102px;">
  	  <?php 
  	  if($this->mode == 'monthly') :	
  	  ?>
	  <div class="fc-day-number vkNgine-modal" data-action="<?= $this->action; ?>" data-target="daydetail" data-date="<?= $this->date; ?>"><?= $this->day->thisDay(); ?></div>
	  <?php 
	  endif;
	  ?>
  	  <div class="fc-day-content">
	  	<div style="position:relative">
		  <?php 	
              foreach($this->days as $day) {
                    
				$activity = $firstRow = $secondRow = null;
				
				if(0 != $day['workoutId']) {
				    if(!empty($this->workoutDetail[$day['workoutId']]))
    					$firstRow .= $this->workoutDetail[$day['workoutId']];
				    
					$secondRow = $this->t->_('Day') . ' ' . $day['workoutDay'];
				}
				else if(0 == $day['workoutId']) {
					if($day['type'] == 'Notes') {
						$firstRow = 'Notes ';
						$secondRow = $day['moreDetails'];
					}
					else {
						$activity = true;
						$firstRow .= $this->t->_($day['type']);
					}	
				}
				
				echo '
					<div data-id="' . $day['id'] . '" data-target="viewdetail" class="fc-event fc-event-skin fc-event-hori fc-corner-left fc-corner-right vkNgine-modal" style="background-color: rgb(71, 125, 174); border-color: rgb(14, 105, 161); top: 30px; -moz-user-select: none;">
						<div class="fc-event-inner fc-event-skin" style="background-color:#477dae;border-color:#0E69A1">
				';
					if(!empty($activity)) {
						$miles = $day['miles'];
						$hour = $day['timeSpentHour'];
						$min = $day['timeSpentMin'];
						
						$detailMiles = $miles ? $miles . ' miles' : '';
						
						$detailClock = null;
						if($min && $hour) {
							$detailClock = $hour . '::' . $min . ' hour';  
						} elseif($min) {
							$detailClock = $min . ' minutes';
						} elseif($hour) {
							$detailClock = $hour . ' hours';
						}
						
						$detailClock = $detailMiles ? '|' . $detailClock : $detailClock; 
						
						echo '
							<span class="fc-event-time"> ' . $this->t->_($day['type']) . ' ' . $detailMiles . $detailClock . '</span>
							' . (($firstRow != $this->t->_($day['type'])) ? '<span class="fc-event-title"> ' . $firstRow . '</span>' : '') . '
						';
					}
					else {
						echo '								
							<span class="fc-event-time"> ' . $firstRow . '</span>
							<span class="fc-event-time"> -- </span>
							<span class="fc-event-title"> ' . $secondRow . '</span>
						';
					}
				echo '
						</div>
					</div>
					';
                }
			?>				
			</div>
		</div>
	</div>
</td>