<td <?= $this->cssBgColor; ?> data-date=<?= $this->date; ?> data-action="<?= $this->action; ?>" data-target="addexercise" class="<?= $this->class; ?> vkNgine-modal fc-widget-content <?= $this->highlightedCss; ?> <?= $this->firstLast; ?> ">
  <div style="min-height: 102px;">
  	  <?php 
  	  if($this->mode == 'monthly') :	
  	  ?>
	  <div class="fc-day-number vkNgine-modal" data-action="<?= $this->action; ?>" data-target="daydetail" data-date="<?= $this->date; ?>"><?= $this->day->thisDay(); ?></div>
	  <?php 
	  endif;
	  ?>
  	  <div class="fc-day-content">
	  	<div style="position:relative">
		  <?php 
		  	for($i=0; $i<count($this->days); $i++) {
				$firstRow = null;
				
				if(0 != $this->days[$i]['workoutId']) {
					$firstRow .= $this->workoutDetail[$this->days[$i]['workoutId']];
					$secondRow = $this->t->_('Day') . ' ' . $this->days[$i]['workoutDay'];
				}
				elseif(0 == $this->days[$i]['workoutId']) {
					$activity = true;
					$firstRow .= $this->t->_($this->days[$i]['type']);	
				}
				
				echo '
					<div data-id="' . $this->days[$i]['id'] . '" data-target="viewdetail" class="fc-event fc-event-skin fc-event-hori fc-corner-left fc-corner-right vkNgine-modal" style="background-color: rgb(71, 125, 174); border-color: rgb(14, 105, 161); top: 30px; -moz-user-select: none;">
						<div class="fc-event-inner fc-event-skin" style="background-color:#477dae;border-color:#0E69A1">
				';
					if(isset($activity)) {
						$miles = $this->days[$i]['miles'];
						$hour = $this->days[$i]['timeSpentHour'];
						$min = $this->days[$i]['timeSpentMin'];
						
						$detailMiles = $miles ? $miles . ' miles' : '';
						
						$detailClock = null;
						if($min && $hour) {
							$detailClock = $hour . '::' . $min . ' hour';  
						} elseif($min) {
							$detailClock = $min . ' minutes';
						} elseif($hour) {
							$detailClock = $hour . ' hours';
						}
						
						$detailClock = $detailMiles ? '|' . $detailClock : $detailClock; 
						
						echo '
							<span class="fc-event-time"> ' . $this->t->_($this->days[$i]['type']) . ' ' . $detailMiles . $detailClock . '</span>
							' . (($firstRow != $this->t->_($this->days[$i]['type'])) ? '<span class="fc-event-title"> ' . $firstRow . '</span>' : '') . '
						';
					}
					else {
						echo '								
							<span class="fc-event-time"> ' . $firstRow . '</span>
							<span class="fc-event-time"> -- </span>
							<span class="fc-event-title"> ' . $secondRow . '</span>
						';
					}
				echo '
						</div>
					</div>
					';
			}
			
			for($k=0; $k<count($this->details); $k++) {
				if($this->details[$k]['type'] == 'SUPPLEMENT'){
					echo '
						<div data-id="' . $this->details[$k]['id'] . '" data-target="viewdaydetail" class="fc-event fc-event-skin fc-event-hori fc-corner-left fc-corner-right vkNgine-modal" style="background-color: rgb(71, 125, 174); border-color: rgb(14, 105, 161); top: 30px; -moz-user-select: none;">
							<div class="fc-event-inner fc-event-skin" style="background-color:#477dae;border-color:#0E69A1">
								<span class="fc-event-time">' . $this->t->_('Supplement Taken') .'</span>
								<span class="fc-event-title">' . $this->details[$k]['value'] . '</span>
							</div>
						</div>
					';
				}
			}
			?>				
			</div>
		</div>
	</div>
</td>