<?= $this->partial('_page_icons.phtml', array('t' 		=> $this->t,
											  'back' 	=> $this->publicUrl(null, 'calendar'),
										      'ajax'    => $this->publicUrl('add-daily', 'calendar') . '/date/' . $this->param['date'])); 
?>

<div class="full-width no-padding">
	<h4 class="shadow"><?= $this->t->_('Adding Daily Workout lower'); ?> :: <?= date('m-d-Y', strtotime($this->param['date'])); ?></h4>
	<div class="decoration decoration-less-padding"></div>
</div>

<?= $this->form; ?>

<script>
$(document).ready(function(){
	var options = {  
		url: '<?= $this->form->getAction(); ?>',
        success: vkNgineAjaxFormSubmit,
		dataType : 'json'
    };
    
	$('#<?= $this->form->getId(); ?>').ajaxForm(options);

	$('#workoutDay-label').hide();
	$('#workoutDay-element').hide();

	$(".setdays").change(function(){
		var selected = $(".setdays option:selected");    
		if(selected.val()){
			$('#workoutDay-element').show();
			
			$.ajax({ 
				url: '/calendar/set-workout-day/id/' + selected.val(),
				success: function(returnData) {
					$('dd#workoutDay-element').html(returnData);
				}
			})
		}
		else {
			$('#workoutDay-label').hide();
			$('#workoutDay-element').hide();
		}
	});
});
</script>

