<?php 
$state = null;
if(isset($this->params['day'])) {
	if (date('d') == $this->params['day']){
		$state = 'fc-state-disabled';
	}
}

$prevMonth = $this->links['prev'];
if($prevMonth->thisMonth() == date('n')){
	$dayPrev = date('d');
}
else {
	$dayPrev = 0;
}

$nextMonth = $this->links['next'];
if($nextMonth->thisMonth() == date('n')){
	$dayNext = date('d');
}
else {
	$dayNext = 0;
}

$today =  '/calendar';
$prev = '/calendar/index/year/' . $prevMonth->thisYear().'/month/'.$prevMonth->thisMonth().'/day/'.$dayPrev;
$next = '/calendar/index/year/' . $nextMonth->thisYear().'/month/'.$nextMonth->thisMonth().'/day/'.$dayNext;
?>
	
<script>
	$(function() {
		$('.fc-button-prev').bind('click', function() {
			window.top.location = '<?= $prev; ?>';
		});
		$('.fc-button-next').bind('click', function() {
			window.top.location = '<?= $next; ?>';
		});
		$('.fc-button-today').bind('click', function() {
			window.top.location = '<?= $today; ?>';
		});
		$('.fc-button-month').bind('click', function() {
			window.top.location = '<?= $this->publicUrl('monthly', 'calendar'); ?>';
		});
		$('.fc-button-agendaWeek').bind('click', function() {
			window.top.location = '<?= $this->publicUrl('weekly', 'calendar'); ?>';
		});

		<?php
			if(!isset($this->params['month'])) :
		?>
			$('.fc-button-today').addClass('fc-state-disabled');
		<?php endif; ?>
							
		$("table.fc-border-separate tbody tr:first").addClass('fc-first');	
		$("table.fc-border-separate tbody tr:last").addClass('fc-last');

		$('.addExercise').bind('click', function() {
			$('#addexercise_dialog').modal('show');
			lnk_addExercise($(this).attr('rel'), '<?= $this->t->_('Adding Daily Workout: '); ?> ' + $(this).attr('rel'), '<?= $this->param['action']; ?>');
		});	

		$('.viewDetail').bind('click', function() {
			$('#viewDetails-dialog').modal('show');
			lnk_viewDetail($(this).attr('rel'), '<?= $this->t->_('Error Message')?>', '<?= $this->t->_('Exercise was successfully deleted')?>');
			return false;
		});

		$('.viewDayDetail').bind('click', function() {
			lnk_viewDayDetail('<?= $this->t->_('Delete'); ?>', '<?= $this->t->_('Close'); ?>', $(this).attr('rel'), '<?= $this->t->_('Day Details'); ?>', '<?= $this->t->_('Error Message')?>', '<?= $this->t->_('Day detail was successfully deleted')?>');
			return false;
		});

		$('.dayDetail').bind('click', function() {
			day = $(this).attr('rel');
			date = explode('-', $(this).attr('rel'));
			dateStr = date[1] + '/' + date[2] + '/' + date[0];
			lnk_dayDetail('<?= $this->t->_('Save'); ?>', '<?= $this->t->_('Close'); ?>', day, '<?= $this->t->_('Adding Day Details: '); ?> ' + dateStr, '<?= $this->param['action']; ?>');
			return false;				
		});
	});
</script>

<?= $this->partial('_breadcrumbs.phtml', 
		array('t' 		  => $this->t,
			  'pageTitle' => $this->t->_('Exercise Calendar'),
			  'page'	  => $this->t->_('Monthly Calendar'),
			  'page2'     => $this->t->_('Exercise Calendar'),
			  'page2href' => '',
	)); 
?>

<div class="row-fluid">
	<div class="span12">			
		<div class="portlet box blue calendar">
			<div class="portlet-title">
				<div class="caption">
					<i class="icon-calendar"></i>
					<span class="hidden-480">
					<?php
						echo
						$this->partial('calendar/_calendarHeader.phtml',
								array('t'        => $this->t,
									  'mode'     => 'monthly',
									  'calendar' => $this->calendar
								));
			    	?>
					</span>
				</div> 							
		</div>
		<div class="portlet-body light-grey">
			<div class="row-fluid">
				<div id="calendar" class="has-toolbar">
					<table class="fc-header" style="width: 100%;">
						<tbody>
							<tr>
								<td class="fc-header-left"></td>
								<td class="fc-header-center"></td>
								<td class="fc-header-right">
									<span class="fc-button fc-button-prev fc-state-default fc-corner-left" unselectable="on"><span class="fc-text-arrow">&lt;</span></span><span class="fc-button fc-button-next fc-state-default" unselectable="on"><span class="fc-text-arrow">&gt;</span></span><span class="fc-button fc-button-today fc-state-default <?= $state; ?>" unselectable="on"><?= $this->t->_('today'); ?></span><span class="fc-button fc-button-month fc-state-active fc-state-default" unselectable="on"><?= $this->t->_('month'); ?></span><span class="fc-button fc-button-agendaWeek fc-state-default" unselectable="on"><?= $this->t->_('week'); ?></span>
							</tr>
						</tbody>
					</table>
					<div class="fc-content" style="position: relative; min-height: 1px;">
						<div class="fc-view fc-view-month fc-grid" style="position: relative; -moz-user-select: none;">
							<table class="fc-border-separate" style="width:100%">
								<thead>
									<tr class="fc-first fc-last">
										<th style="width: 127px;" class="fc-widget-header fc-first"><?= $this->t->_('Monday'); ?></th>
										<th style="width: 127px;" class="fc-widget-header"><?= $this->t->_('Tuesday'); ?></th>
										<th style="width: 127px;" class="fc-widget-header"><?= $this->t->_('Wednesday'); ?></th>
										<th style="width: 127px;" class="fc-widget-header"><?= $this->t->_('Thursday'); ?></th>
										<th style="width: 127px;" class="fc-widget-header"><?= $this->t->_('Friday'); ?></th>
										<th style="width: 127px;" class="fc-widget-header"><?= $this->t->_('Saturday'); ?></th>
										<th style="width: 127px;" class="fc-widget-header fc-last"><?= $this->t->_('Sunday'); ?></th>
									</tr>
								</thead>
								<tbody>
									<?php
										while($day = $this->calendar->fetch()) {
											$modelDailyExercises = new Public_Model_Daily_Exercises();
											$modelDailyDetails = new Public_Model_Daily_Details();
											
											$thisMonth = ((strlen($day->thisMonth()) == 1) ? '0'. $day->thisMonth() : $day->thisMonth());
											$thisDay = ((strlen($day->thisDay()) == 1) ? '0'. $day->thisDay() : $day->thisDay());
											
											$date = $day->thisYear() . '-' . $thisMonth . '-' . $thisDay;
											
											$days = $modelDailyExercises->fetchByDate($date, $this->user);							
											$details = $modelDailyDetails->fetchByDate($date, $this->user);
											
											$firstLast = null;
												
											if($day->isLast()) {
												$firstLast = 'fc-last';
											}
											if($day->isFirst()) {
												$firstLast = 'fc-first';
											}
											
											if($day->isFirst())
												echo "<tr>\n";
											
											if($day->isSelected()) {
												$class = 'fc-state-highlight ';
											}
											elseif($day->isEmpty()) {
												$class = 'fc-other-month';											
											}
											else {
												$class = '';												
											}
										    
										    $highlightedCss = null;
										    $highlightedCss = ($date == date('Y-m-d')) ? 'fc-state-highlight' : '';
										    
										    $cssBgColor = null;
										    $j = null;
										    for($k=0; $k<count($details); $k++) {
										    	if($details[$k]['type'] == 'COLOR') {
										    		$cssBgColor = 'style="background-color:' . $details[$k]['value'] . ' "';
										    	}
										    }
						        	
									    	echo
										    	$this->partial('calendar/_renderDay.phtml',
										    			array('t'         		=> $this->t,
										    				  'day'   	  	    => $day,
														      'date'      		=> $date,
															  'class'  		    => $class,
															  'mode'            => 'monthly',
										    				  'firstLast'		=> $firstLast,
										    				  'details' 		=> $details,
															  'cssBgColor'      => $cssBgColor,
														      'highlightedCss'  => $highlightedCss,
										    			));
						    					    
										    if ( $day->isLast() )
										        echo "</tr>\n";						        
					   					}						
											?>
										</tbody>	
									</table>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
			
	<?php 
		if(0 != count($this->otherdata)) :
	?>
      <div class="row-fluid">
	      <div class="span12">
			  <div class="portlet">
			  	<div class="portlet-title">
			  		<div class="caption">
			  			<i class="icon-male"></i>
			  			<?= $this->t->_('Other Monthly Recorded Data'); ?>		
			  		</div>
			    </div>
			    <div class="portlet-body">
				  <table class="table table-striped table-hover">
				    <thead>
				      <tr>
				        <th><?= $this->t->_('Value'); ?></th>
						<th><?= $this->t->_('Type'); ?></th>
						<th><?= $this->t->_('Record Date'); ?></th>
				      </tr>
				    </thead>
				    <tbody>
		      		<?php
						foreach($this->otherdata as $data) :
					?>	
						<tr>
							<td><?= $data['value']?></td>
							<td><?= ($data['type'] == 'WEIGHT') ? $this->t->_('Weight') : $this->t->_('Not Entered'); ?></td>
							<td><?= $this->escape($this->dateFormat($data['date'], Zend_Date::DATE_FULL)); ?></td>
						</tr>
					<?php 
						endforeach;
					?>
		      	    </tbody>
	      	     </table>
	      	  </div>
	      </div>	      
		</div>
	</div>
	<?php endif; ?>
	