<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
	<h3 id="myModalLabel3"><?= $this->t->_('Workout Details'); ?>: <?= date('m-d-Y', strtotime($this->detail['date'])); ?></h3>
</div>
<div class="modal-body">
	<table class="table table-striped table-bordered table-advance table-hover">
  	    <thead>
            <tr>
            	<?php
		    		if($this->detail['workoutId']) :
		    	?>
                	<th style="width:150px;"><?= $this->t->_('Workout Name'); ?></th>
                <?php endif; ?>
               
                <?php 
		    		if($this->detail['workoutDay']) :
		    	?>	
               		<th style="width:50px;"><?= $this->t->_('Workout Day'); ?></th>
                <?php endif; ?>
               	
                <?php
		    		if($this->detail['type']) :
		    	?>
                	<th style="width:50px;"><?= $this->t->_('Type'); ?></th>
                <?php endif; ?>
                
                <?php
		    		if($this->detail['moreDetails']) :
		    	?>
                	<th style="width:50px;"><?= $this->t->_('Additional Details'); ?></th>
                <?php endif; ?>
                
                <?php
		    		if($this->detail['timeSpentHour'] || $this->detail['timeSpentMin']) :
		    	?>
                	<th style="width:50px;"><?= $this->t->_('Duration'); ?></th>
                <?php endif; ?>
                
                <?php
		    		if($this->detail['miles']) :
		    	?>
                	<th style="width:50px;"><?= $this->t->_('Miles Ran'); ?></th>
                <?php endif; ?>
            </tr>
        </thead>
        <tbody>
             <tr>
             	 <?php 
		    		if($this->detail['workoutId']) :
		    	 ?>
                 <td>
                    <a href="<?= $this->publicUrl('view-workout', 'my-account'); ?>/id/<?= $this->detail['workoutId']; ?>"><?= $this->workoutDetail['name'] ?></a>
                 </td>
                 <?php endif; ?>
                 <?php 
		    		if($this->detail['workoutDay']) :
		    	 ?>
                 <td>
                 	<?= $this->detail['workoutDay'] ?>
                 </td>
                 <?php endif; ?>
                 <?php
		    		if($this->detail['type']) :
		    	 ?>
                 <td>
                 	<?= $this->t->_($this->detail['type']) ?>
                 </td>
                 <?php endif; ?>
                 <?php
		    		if($this->detail['moreDetails']) :
		    	 ?>
                 <td>
                 	<?= nl2br($this->detail['moreDetails']); ?>
                 </td>
                 <?php endif; ?>
                 <?php
		    		if($this->detail['timeSpentHour'] || $this->detail['timeSpentMin']) :
		    	 ?>
                	<td><?= $this->detail['timeSpentHour']; ?>:<?= $this->detail['timeSpentMin']; ?></td>
                <?php endif; ?>
                <?php
		    		if($this->detail['miles']) :
		    	 ?>
                	<td><?= $this->detail['miles']; ?></td>
                <?php endif; ?>                
             </tr>
        </tbody>            
    </table>
</div>
<div class="modal-footer">
	<button class="btn" data-dismiss="modal" aria-hidden="true"><?= $this->t->_('Close'); ?></button>	
	<button class="btn red submit" type="button"><?= $this->t->_('Delete'); ?></button>
</div>

<script>
	vkNgineModals.calendar('delete-daily-exercise');
</script>