<?= $this->partial('_modals.phtml', 
				array('t' 		  => $this->t,					  
					  'headline'  => 'Add Selected Exercises to Workouts',
					  'content'   => $this->form
	)); 
?>

<script>
$(document).ready(function(){
	$('.btn-primary').bind('click', function() {
		$('#add_selected_workouts_dialog').hide();
		$('#add_selected_workouts_dialog').removeClass('in');
		$('#add_selected_workouts_dialog').attr('aria-hidden', 'true');
		$('div.modal-backdrop').hide();		
		$('#<?= $this->form->getId(); ?>').submit();
	});
	
	var options = {  
		url: '<?= $this->form->getAction(); ?>',
        success: vkNgineAjaxFormSubmit,
		dataType : 'json'
    };
    
	$('#<?= $this->form->getId(); ?>').ajaxForm(options);
});

$('label[for="day"]').hide();
$('#day').hide();
$('#day').next().hide();

$(".setdays").change(function(){
	var selected = $(".setdays option:selected");    

	if(selected.val()){
		$('label[for="day"]').show();
		$('#day').show();
		$('#day').next().show();
		
		$.ajax({ 
			url: '/index/set-day/id/' + selected.val(),
			success: function(returnData) {
				$('#day').html(returnData);
			}
		})
	}
	else {
		$('label[for="day"]').hide();
		$('#day').hide();
		$('#day').next().hide();
	}
});
</script>

