<?= $this->partial('_modals.phtml', 
				array('t' 		  => $this->t,					  
					  'headline'  => 'Add Selected Exercises to Workouts',
					  'content'   => $this->form
	)); 
?>

<script>
$(document).ready(function(){
	$('.btn-primary').bind('click', function() {
		$('#add_selected_workouts_dialog').hide();
		$('#add_selected_workouts_dialog').removeClass('in');
		$('#add_selected_workouts_dialog').attr('aria-hidden', 'true');
		$('div.modal-backdrop').hide();		
		$('#<?= $this->form->getId(); ?>').submit();
	});
	
	var options = {  
		url: '<?= $this->form->getAction(); ?>',
        success: vkNgineAjaxFormSubmit,
		dataType : 'json'
    };
    
	$('#<?= $this->form->getId(); ?>').ajaxForm(options);
});

$('#day-label').hide();
$('#day-element').hide();

$(".setdays").change(function(){
	var selected = $(".setdays option:selected");    

	if(selected.val()){
		
		$('#day-element').show();
		
		$.ajax({ 
			url: '/index/set-day/id/' + selected.val(),
			success: function(returnData) {
				$('dd#day-element').html(returnData);
			}
		})
	}
	else {
		$('#day-label').hide();
		$('#day-element').hide();
	}
});
</script>

