<?= $this->partial('_breadcrumbs.phtml', 
				array('t' 		  => $this->t,					 
					  'page'	  => $this->t->_('Exercises'),
					  'page2'     => $this->params['type'],
					  'page2href' => '/index/exercises/type/' . $this->exercise['primaryMuscle']
	)); 
?>

<div id="page" class="dashboard">
	<div class="row-fluid">
		<div class="span12">			
			<div class="widget">				
				<div class="widget-body">
					<table class="table table-striped table-bordered" id="sample_1">
						<thead>
					      <tr>
					        <th>&nbsp;</th>
							<th><?= $this->t->_('Exercise Name'); ?></th>
						    <th><?= $this->t->_('Primary Muscle'); ?></th> 
						    <th><?= $this->t->_('Secondary Muscle'); ?></th> 
						    <th><?= $this->t->_('Mechanics'); ?></th>
						    <th><?= $this->t->_('Equipment Used'); ?></th>
					      </tr>
					    </thead>
					    
					    <tbody>
						    <?php
							    if($this->params['type'] != 'Legs'){
							    	$this->params['type'] = "primaryMuscle LIKE '%" . $this->params['type'] . "%'";
							    }
							    else {
							    	$this->params['type'] = "primaryMuscle LIKE '%Hamstrings%' or primaryMuscle LIKE '%Glutes, Hamstrings, Quadriceps%' or primaryMuscle LIKE '%Quadriceps%' or primaryMuscle LIKE '%Glutes%'";
							    }
								foreach($this->exercises->fetchAll($this->params['type'])->toArray() as $exercise):
							?>	
						      <tr>
						        <td><input type="checkbox" name="exercises[]" value="<?= $exercise['exerciseId']; ?>"></td>
								<td><a href="<?= $this->publicUrl('view', 'index') ?>/id/<?= $exercise['exerciseId']; ?>/tab/<?= $this->tab; ?>"><?= $exercise['name']; ?></a></td>
								<td><?= $this->t->_($exercise['primaryMuscle']); ?></td>
								<td><?= (($exercise['secondaryMuscle'] != 'None') ? $this->t->_($exercise['secondaryMuscle']) : ''); ?></td>
								<td><?= $this->t->_($exercise['mechanics']); ?></td>
								<td><?= $this->t->_($exercise['equipmentUsed']); ?></td>
						      </tr>
						    <?php 
								endforeach;
							?>
		    			</tbody>
					</table>
					<div>
						<a class="btn_add_selected_workouts" href="#">
							<?= $this->t->_('Add Selected Exercises to a Workout');?>
						</a>
				    </div>
				</div>
			</div>
		</div>
	</div>
</div>

<script>
$('.btn_add_selected_workouts').bind('click', function() {
	btn_add_selected_workouts('<?= $this->t->_('Add'); ?>', '<?= $this->t->_('Cancel'); ?>');
});	
</script>