<?=
$this->headScript()
		->appendFile($this->baseUrl('/js/mobile/exercises.m.js'));
?>

<?= $this->partial('_page_icons.phtml', array('t' 		=> $this->t,
											  'back' 	=> false,
										      'ajax'    => $this->publicUrl('exercises', 'index'))); 
?>

<link href="/css/mobile/iphone.css" media="screen" rel="stylesheet" type="text/css" >

	<h4 class="shadow"><?= $this->t->_('Exercises'); ?></h4>
	<div class="decoration decoration-less-padding"></div>
	
	<div id="exercises">
	<?php 
		if(vkNgine_Config::getSystemConfig()->language->locale == 'en') :
	?>
		<h4> <?= $this->t->_('Abdominals'); ?><sup class="exercise-count"><?= count($this->exercises->fetchAll("primaryMuscle LIKE '%Abs%'")) . '' ?></sup></h4>
		
		<ul>
		<?php
		    foreach($this->exercises->fetchAll("primaryMuscle LIKE '%Abs%'")->toArray() as $exercise):
		?>	
			<li class="arrow"><a class="loadexercises" rel="<?= $this->publicUrl('view', 'index') ?>/id/<?= $exercise['exerciseId']; ?>"><?= $exercise['name']; ?></a></li>
		 
	    <?php 
			endforeach;
		?>
		</ul>
		
		<h4> <?= $this->t->_('Back'); ?><sup class="exercise-count"><?= count($this->exercises->fetchAll("primaryMuscle LIKE '%Back%'")) . '' ?></sup></h4>
		
		<ul>
		<?php
		    foreach($this->exercises->fetchAll("primaryMuscle LIKE '%Back%'")->toArray() as $exercise):
		?>	
			<li class="arrow"><a class="loadexercises" rel="<?= $this->publicUrl('view', 'index') ?>/id/<?= $exercise['exerciseId']; ?>"><?= $exercise['name']; ?></a></li>
		 
	    <?php 
			endforeach;
		?>
		</ul>
		
		<h4> <?= $this->t->_('Biceps'); ?><sup class="exercise-count"><?= count($this->exercises->fetchAll("primaryMuscle LIKE '%Biceps%'")) . '' ?></sup></h4>
		
		<ul>
		<?php
		    foreach($this->exercises->fetchAll("primaryMuscle LIKE '%Biceps%'")->toArray() as $exercise):
		?>	
			<li class="arrow"><a class="loadexercises" rel="<?= $this->publicUrl('view', 'index') ?>/id/<?= $exercise['exerciseId']; ?>"><?= $exercise['name']; ?></a></li>
		 
	    <?php 
			endforeach;
		?>
		</ul>
		
		<h4> <?= $this->t->_('Calves'); ?><sup class="exercise-count"><?= count($this->exercises->fetchAll("primaryMuscle LIKE '%Calves%'")) . '' ?></sup></h4>
		
		<ul>
		<?php
		    foreach($this->exercises->fetchAll("primaryMuscle LIKE '%Calves%'")->toArray() as $exercise):
		?>	
			<li class="arrow"><a class="loadexercises" rel="<?= $this->publicUrl('view', 'index') ?>/id/<?= $exercise['exerciseId']; ?>"><?= $exercise['name']; ?></a></li>
		 
	    <?php 
			endforeach;
		?>
		</ul>
		
		<h4> <?= $this->t->_('Chest'); ?><sup class="exercise-count"><?= count($this->exercises->fetchAll("primaryMuscle LIKE '%Chest%'")) . '' ?></sup></h4>
		
		<ul>
		<?php
		    foreach($this->exercises->fetchAll("primaryMuscle LIKE '%Chest%'")->toArray() as $exercise):
		?>	
			<li class="arrow"><a class="loadexercises" rel="<?= $this->publicUrl('view', 'index') ?>/id/<?= $exercise['exerciseId']; ?>"><?= $exercise['name']; ?></a></li>
		 
	    <?php 
			endforeach;
		?>
		</ul>
		
		<h4> <?= $this->t->_('Forearms'); ?><sup class="exercise-count"><?= count($this->exercises->fetchAll("primaryMuscle LIKE '%Forearms%'")) . '' ?></sup></h4>
		
		<ul>
		<?php
		    foreach($this->exercises->fetchAll("primaryMuscle LIKE '%Forearms%'")->toArray() as $exercise):
		?>	
			<li class="arrow"><a class="loadexercises" rel="<?= $this->publicUrl('view', 'index') ?>/id/<?= $exercise['exerciseId']; ?>"><?= $exercise['name']; ?></a></li>
		 
	    <?php 
			endforeach;
		?>
		</ul>
		
		<h4> <?= $this->t->_('Legs'); ?><sup class="exercise-count"><?= count($this->exercises->fetchAll("primaryMuscle LIKE '%Hamstrings%' or primaryMuscle LIKE '%Glutes, Hamstrings, Quadriceps%' or primaryMuscle LIKE '%Quadriceps%' or primaryMuscle LIKE '%Glutes%'")) . '' ?></sup></h4>
		
		<ul>
		<?php
			$this->params['type'] = "primaryMuscle LIKE '%Hamstrings%' or primaryMuscle LIKE '%Glutes, Hamstrings, Quadriceps%' or primaryMuscle LIKE '%Quadriceps%' or primaryMuscle LIKE '%Glutes%'";
			
		    foreach($this->exercises->fetchAll($this->params['type'])->toArray() as $exercise):
		?>	
			<li class="arrow"><a class="loadexercises" rel="<?= $this->publicUrl('view', 'index') ?>/id/<?= $exercise['exerciseId']; ?>"><?= $exercise['name']; ?></a></li>
		 
	    <?php 
			endforeach;
		?>
		</ul>
		
		<h4> <?= $this->t->_('Shoulders'); ?><sup class="exercise-count"><?= count($this->exercises->fetchAll("primaryMuscle LIKE '%Shoulders%'")) . '' ?></sup></h4>
		
		<ul>
		<?php
		    foreach($this->exercises->fetchAll("primaryMuscle LIKE '%Shoulders%'")->toArray() as $exercise):
		?>	
			<li class="arrow"><a class="loadexercises" rel="<?= $this->publicUrl('view', 'index') ?>/id/<?= $exercise['exerciseId']; ?>"><?= $exercise['name']; ?></a></li>
		 
	    <?php 
			endforeach;
		?>
		</ul>
		
		<h4> <?= $this->t->_('Traps'); ?><sup class="exercise-count"><?= count($this->exercises->fetchAll("primaryMuscle LIKE '%Traps%'")) . '' ?></sup></h4>
		
		<ul>
		<?php
		    foreach($this->exercises->fetchAll("primaryMuscle LIKE '%Traps%'")->toArray() as $exercise):
		?>	
			<li class="arrow"><a class="loadexercises" rel="<?= $this->publicUrl('view', 'index') ?>/id/<?= $exercise['exerciseId']; ?>"><?= $exercise['name']; ?></a></li>
		 
	    <?php 
			endforeach;
		?>
		</ul>
		
		<h4> <?= $this->t->_('Triceps'); ?><sup class="exercise-count"><?= count($this->exercises->fetchAll("primaryMuscle LIKE '%Triceps%'")) . '' ?></sup></h4>
		
		<ul>
		<?php
		    foreach($this->exercises->fetchAll("primaryMuscle LIKE '%Triceps%'")->toArray() as $exercise):
		?>	
			<li class="arrow"><a class="loadexercises" rel="<?= $this->publicUrl('view', 'index') ?>/id/<?= $exercise['exerciseId']; ?>"><?= $exercise['name']; ?></a></li>
		 
	    <?php 
			endforeach;
		?>
		</ul>
	<?php else :?>
		<h4> <?= $this->t->_('Abdominals'); ?><sup class="exercise-count"><?= count($this->exercises->fetchAll("primaryMuscle LIKE '%Abs%'")) . '' ?></sup></h4>
		
		<ul>
		<?php
		    foreach($this->exercises->fetchAll("primaryMuscle LIKE '%Abs%'")->toArray() as $exercise):
		?>	
			<li class="arrow"><a class="loadexercises" rel="<?= $this->publicUrl('view', 'index') ?>/id/<?= $exercise['exerciseId']; ?>"><?= $exercise['name']; ?></a></li>
		 
	    <?php 
			endforeach;
		?>
		</ul>
		
		<h4> <?= $this->t->_('Legs'); ?><sup class="exercise-count"><?= count($this->exercises->fetchAll("primaryMuscle LIKE '%Hamstrings%' or primaryMuscle LIKE '%Glutes, Hamstrings, Quadriceps%' or primaryMuscle LIKE '%Quadriceps%' or primaryMuscle LIKE '%Glutes%'")) . '' ?></sup></h4>
		
		<ul>
		<?php
			$this->params['type'] = "primaryMuscle LIKE '%Hamstrings%' or primaryMuscle LIKE '%Glutes, Hamstrings, Quadriceps%' or primaryMuscle LIKE '%Quadriceps%' or primaryMuscle LIKE '%Glutes%'";
			
		    foreach($this->exercises->fetchAll($this->params['type'])->toArray() as $exercise):
		?>	
			<li class="arrow"><a class="loadexercises" rel="<?= $this->publicUrl('view', 'index') ?>/id/<?= $exercise['exerciseId']; ?>"><?= $exercise['name']; ?></a></li>
		 
	    <?php 
			endforeach;
		?>
		</ul>
		
		<h4> <?= $this->t->_('Calves'); ?><sup class="exercise-count"><?= count($this->exercises->fetchAll("primaryMuscle LIKE '%Calves%'")) . '' ?></sup></h4>
		
		<ul>
		<?php
		    foreach($this->exercises->fetchAll("primaryMuscle LIKE '%Calves%'")->toArray() as $exercise):
		?>	
			<li class="arrow"><a class="loadexercises" rel="<?= $this->publicUrl('view', 'index') ?>/id/<?= $exercise['exerciseId']; ?>"><?= $exercise['name']; ?></a></li>
		 
	    <?php 
			endforeach;
		?>
		</ul>
		
		<h4> <?= $this->t->_('Chest'); ?><sup class="exercise-count"><?= count($this->exercises->fetchAll("primaryMuscle LIKE '%Chest%'")) . '' ?></sup></h4>
		
		<ul>
		<?php
		    foreach($this->exercises->fetchAll("primaryMuscle LIKE '%Chest%'")->toArray() as $exercise):
		?>	
			<li class="arrow"><a class="loadexercises" rel="<?= $this->publicUrl('view', 'index') ?>/id/<?= $exercise['exerciseId']; ?>"><?= $exercise['name']; ?></a></li>
		 
	    <?php 
			endforeach;
		?>
		</ul>
		
		<h4> <?= $this->t->_('Shoulders'); ?><sup class="exercise-count"><?= count($this->exercises->fetchAll("primaryMuscle LIKE '%Shoulders%'")) . '' ?></sup></h4>
		
		<ul>
		<?php
		    foreach($this->exercises->fetchAll("primaryMuscle LIKE '%Shoulders%'")->toArray() as $exercise):
		?>	
			<li class="arrow"><a class="loadexercises" rel="<?= $this->publicUrl('view', 'index') ?>/id/<?= $exercise['exerciseId']; ?>"><?= $exercise['name']; ?></a></li>
		 
	    <?php 
			endforeach;
		?>
		</ul>
		
		<h4> <?= $this->t->_('Forearms'); ?><sup class="exercise-count"><?= count($this->exercises->fetchAll("primaryMuscle LIKE '%Forearms%'")) . '' ?></sup></h4>
		
		<ul>
		<?php
		    foreach($this->exercises->fetchAll("primaryMuscle LIKE '%Forearms%'")->toArray() as $exercise):
		?>	
			<li class="arrow"><a class="loadexercises" rel="<?= $this->publicUrl('view', 'index') ?>/id/<?= $exercise['exerciseId']; ?>"><?= $exercise['name']; ?></a></li>
		 
	    <?php 
			endforeach;
		?>
		</ul>
		
		<h4> <?= $this->t->_('Biceps'); ?><sup class="exercise-count"><?= count($this->exercises->fetchAll("primaryMuscle LIKE '%Biceps%'")) . '' ?></sup></h4>
		
		<ul>
		<?php
		    foreach($this->exercises->fetchAll("primaryMuscle LIKE '%Biceps%'")->toArray() as $exercise):
		?>	
			<li class="arrow"><a class="loadexercises" rel="<?= $this->publicUrl('view', 'index') ?>/id/<?= $exercise['exerciseId']; ?>"><?= $exercise['name']; ?></a></li>
		 
	    <?php 
			endforeach;
		?>
		</ul>
		
		<h4> <?= $this->t->_('Triceps'); ?><sup class="exercise-count"><?= count($this->exercises->fetchAll("primaryMuscle LIKE '%Triceps%'")) . '' ?></sup></h4>
		
		<ul>
		<?php
		    foreach($this->exercises->fetchAll("primaryMuscle LIKE '%Triceps%'")->toArray() as $exercise):
		?>	
			<li class="arrow"><a class="loadexercises" rel="<?= $this->publicUrl('view', 'index') ?>/id/<?= $exercise['exerciseId']; ?>"><?= $exercise['name']; ?></a></li>
		 
	    <?php 
			endforeach;
		?>
		</ul>
		
		<h4> <?= $this->t->_('Back'); ?><sup class="exercise-count"><?= count($this->exercises->fetchAll("primaryMuscle LIKE '%Back%'")) . '' ?></sup></h4>
		
		<ul>
		<?php
		    foreach($this->exercises->fetchAll("primaryMuscle LIKE '%Back%'")->toArray() as $exercise):
		?>	
			<li class="arrow"><a class="loadexercises" rel="<?= $this->publicUrl('view', 'index') ?>/id/<?= $exercise['exerciseId']; ?>"><?= $exercise['name']; ?></a></li>
		 
	    <?php 
			endforeach;
		?>
		</ul>
		
		<h4> <?= $this->t->_('Traps'); ?><sup class="exercise-count"><?= count($this->exercises->fetchAll("primaryMuscle LIKE '%Traps%'")) . '' ?></sup></h4>
		
		<ul>
		<?php
		    foreach($this->exercises->fetchAll("primaryMuscle LIKE '%Traps%'")->toArray() as $exercise):
		?>	
			<li class="arrow"><a class="loadexercises" rel="<?= $this->publicUrl('view', 'index') ?>/id/<?= $exercise['exerciseId']; ?>"><?= $exercise['name']; ?></a></li>
		 
	    <?php 
			endforeach;
		?>
		</ul>
	<?php endif; ?>
	</div>
