<?= $this->partial('_breadcrumbs.phtml', 
				array('t' 		  => $this->t,
					  'pageTitle' => $this->t->_('My Statistics'),
					  'page'	  => $this->t->_('Dashboard'),
					  'calendar'  => true,
	)); 
?>		
<div id="page" class="dashboard">
	<div class="row-fluid">
		<div class="span3 responsive" data-tablet="span6" data-desktop="span3">
			<div class="circle-stat block">
				<div class="visual">
					<input class="knobify" data-width="115" data-thickness=".2" data-skin="tron" data-displayprevious="true" value="11" data-max="31" data-min="1" />
				</div>
				<div class="details">
					<div class="title">Monthly Logs <i class="icon-caret-up"></i></div>
					<div class="number">10112</div>				
				</div>
			</div>
		</div>
		<div class="span3 responsive" data-tablet="span6" data-desktop="span3">
			<div class="circle-stat block">
				<div class="visual">
					<input class="knobify" data-width="115" data-fgcolor="#66EE66" data-thickness=".2" data-skin="tron" data-displayprevious="true" value="12" data-max="31" data-min="1" />
				</div>
				<div class="details">
					<div class="title">Monthly Off Days <i class="icon-caret-up"></i></div>
					<div class="number">987</div>
				</div>
			</div>
		</div>
		<div class="span3 responsive" data-tablet="span6 fix-margin" data-desktop="span3">
			<div class="circle-stat block">
				<div class="visual">
					<input class="knobify" data-width="115" data-fgcolor="#e23e29" data-thickness=".2" data-skin="tron" data-displayprevious="true" value="5" data-max="31" data-min="1" />
				</div>
				<div class="details">
					<div class="title">Monthly On Days <i class="icon-caret-down down"></i></div>
					<div class="number">0.01%</div>
				</div>
			</div>
		</div>
		<div class="span3 responsive" data-tablet="span6" data-desktop="span3">
			<div class="circle-stat block">
				<div class="visual">
					<input class="knobify" data-width="115" data-fgcolor="#fdbb39" data-thickness=".2" data-skin="tron" data-displayprevious="true" value="8" data-max="31" data-min="1" />
				</div>
				<div class="details">
					<div class="title">Weight Change <i class="icon-caret-up"></i></div>
					<div class="number">1120.32$</div>
				</div>
			</div>
		</div>
	</div>
</div>