<?= $this->partial('_breadcrumbs.phtml', 
				array('t' 		  => $this->t,
					  'pageTitle' => $this->t->_('My Statistics'),
					  'page'	  => $this->t->_('Dashboard'),
					  'calendar'  => true,
	));
?>		

<?php
	$this->headScript()
		 	->appendFile($this->baseUrl('/js/public/vkNgine.dashboard.js'));
?>     

<div id="dashboard">
	<!-- BEGIN DASHBOARD STATS -->
	<div class="row-fluid">
		<div class="span3 responsive" data-tablet="span6" data-desktop="span3">
			<div class="dashboard-stat blue">
				<div class="visual">
					<i class="icon-globe"></i>
				</div>
				<div class="details">
					<div class="number"><?= $this->statistics['dailyexercises']; ?></div>
					<div class="desc"><?= $this->t->_('total exercise logs'); ?></div>
				</div>       
			</div>
		</div>
		<div class="span3 responsive" data-tablet="span6" data-desktop="span3">
			<div class="dashboard-stat yellow">
				<div class="visual">
					<i class="icon-truck"></i>
				</div>
				<div class="details">
					<div class="number"><?= $this->statistics['dailydetails']; ?></div>
					<div class="desc"><?= $this->t->_('total other logs'); ?></div>
				</div>          
			</div>
		</div>
		<div class="span3 responsive" data-tablet="span6" data-desktop="span3">
			<div class="dashboard-stat green">
				<div class="visual">
					<i class="icon-caret-down"></i>
				</div>
				<div class="details">
					<div class="number"><?= $this->statistics['workouts']; ?></div>
					<div class="desc"><?= $this->t->_('Workouts'); ?></div>
				</div>
				<a class="more" href="/my-account/my-workouts">
				<?= $this->t->_('Go to My Workouts'); ?> <i class="m-icon-swapright m-icon-white"></i>
				</a>                 
			</div>
		</div>
		<div class="span3 responsive" data-tablet="span6  fix-offset" data-desktop="span3">
			<div class="dashboard-stat purple">
				<div class="visual">
					<i class="icon-bar-chart"></i>
				</div>
				<div class="details">
					<div class="number"><?= $this->statistics['measurements']; ?></div>
					<div class="desc"><?= $this->t->_('Measurements'); ?></div>
				</div>
				<a class="more" href="/my-account/my-measurements">
				<?= $this->t->_('Go to My Measurements'); ?> <i class="m-icon-swapright m-icon-white"></i>
				</a>                 
			</div>
		</div>
		
		<div class="statistics portlet box purple">
        	<div class="portlet-title">
            	<div class="caption"><i class="icon-calendar"></i><?= $this->t->_('Statistics'); ?> -- <?= $this->t->_(date('F')); ?> <?= date('j Y')?> </div>
            </div>
            <div class="portlet-body">
            	<div class="row-fluid">
            		<div class="span1">
                        <div class="charts">
                            <div class="ran" data-percent="<?= $this->statistics['milesRan']; ?>"><span><?= $this->statistics['milesRan']; ?></span></div>
                        	<?= $this->t->_('miles ran'); ?>
                     	</div>
                     </div>
                     <div class="span1">
                     	<div class="charts">
                        	<div class="caloriesconsumed" data-percent="<?= $this->statistics['caloriesConsumed']; ?>"><span><?= $this->statistics['caloriesConsumed']; ?></span></div>
                            <?= $this->t->_('calories consumed'); ?>
                        </div>
                     </div>
                     <div class="span1">
                     	<div class="charts">
                        	<div class="misseddays" data-percent="55"><span>+55</span>%</div>
                            <?= $this->t->_('days went to gym'); ?>
                        </div>
                     </div>
                     <div class="span1">
                     	<div class="charts">
                        	<div class="misseddays" data-percent="55"><span>+55</span>%</div>
                            <?= $this->t->_('days missed out of gym'); ?>
                        </div>
                     </div>
                </div>
            </div>
		</div>
	
<script type="text/javascript">
	var core = new vkNgine.core.engine();
	core.initDashboard();
</script>
	