<?= $this->partial('_page_icons.phtml', array('t' 			=> $this->t,
											  'refreshLink' => $this->publicUrl())); 
?>
	
<div class="full-width">
	<h4 class="shadow"><?= ($this->t->_('My Statistics lower')); ?></h4>
	<div class="decoration"></div>
	<ul class="icon-list shadow">
		<li class="list-info"><?= $this->statistics['workouts']; ?> <?= $this->t->_('Workouts'); ?> </li>
		<li class="list-info"><?= $this->statistics['dailydetails']; ?> <?= $this->t->_('Daily details'); ?></li>
		<li class="list-info"><?= $this->statistics['dailyexercises']; ?> <?= $this->t->_('Daily exercises'); ?></li>
		<li class="list-info"><?= $this->statistics['measurements']; ?> <?= $this->t->_('Measurements'); ?></li>
	</ul>
	<h4 class="shadow"><?= ($this->t->_('App Details')); ?></h4>
	<div class="decoration"></div>
	<ul class="icon-list shadow">
		<li class="list-attention"><?= $this->t->_('App version'); ?> <span class="highlight-gray"><?= vkNgine_Version::APP_VERSION; ?></span></li>
	</ul>
</div>
