<?= 
	$this->partial('_breadcrumbs.phtml', 
		array('t' 		  => $this->t,					  
			  'page'	  => $this->t->_('Search results'),
			  'pageTitle' => $this->t->_('Search results')
	)); 
?>

<div class="row-fluid">
	<div class="span12">
		<div class="portlet-body">					
			<div class="row-fluid">
			<?= sprintf($this->t->_('%s exercises were found'), count($this->results)); ?>
						<hr class="clearfix" />
						<div class="table-responsive">
							<?php if( 0 != count($this->results)): ?>
							<table class="table table-striped table-bordered table-advance table-hover">
								<thead>
									<tr>
										<th><?= $this->t->_('Exercise Name'); ?></th>
									    <th><?= $this->t->_('Primary Muscle'); ?></th> 
									    <th><?= $this->t->_('Secondary Muscle'); ?></th> 
									    <th><?= $this->t->_('Mechanics'); ?></th>
									    <th><?= $this->t->_('Equipment Used'); ?></th>
									</tr>
								</thead>
								<?php 
									foreach($this->results as $exercise):
								?>
									<tr>
										<td><a href="/exercise/<?= $exercise['url']; ?>"><?= $exercise['name']; ?></a></td>
										<td><?= $exercise['primaryMuscle']; ?></td>
										<td><?= $exercise['secondaryMuscle']; ?></td>
										<td><?= $exercise['mechanics']; ?></td>
										<td><?= $exercise['equipmentUsed']; ?></td>
									</tr>
								<?php 
									endforeach;
								?>
							</table>		
							<?php else: ?>
								<?= $this->t->_('No results were found'); ?>
							<?php endif; ?>						
							</div>
						</div>
					</div>
					
					
					
				</div>
			
		
	</div>