<?php
echo $this->headScript()
				->appendFile($this->baseUrl('/js/mobile/view.m.js'));
echo $this->headLink()
				->prependStylesheet($this->baseUrl('/css/mobile/iphone.css'));
?>

<style>
.no-padding {
	padding-bottom:2px;
}
ul {
	margin: 8px 10px 17px 0;
}
ul.field li h3 {
	width:40%
}
ul.field li a {
	width:50%
}
</style>

<?= $this->partial('_page_icons.phtml', array('t' 		=> $this->t,
											  'back' 	=> $this->publicUrl('exercises', 'index'),
											  'ref'     => isset($this->param['ref']) ? $this->param['ref'] : null,
										      'ajax'    => $this->publicUrl('view', 'index') . '/id/' . $this->param['id'])); 
?>

<h3 align="center"><?= $this->exercise['name']; ?></h3>
<div class="decoration decoration-less-padding"></div>

<h4 class="no-padding"><?= $this->t->_('Exercise Details lower'); ?></h4>

<ul class="field">
	<li><h3><?= $this->t->_('Primary Muscle'); ?></h3> <a><?= $this->t->_($this->exercise['primaryMuscle']); ?></a></li>
	<li><h3><?= $this->t->_('Secondary Muscle'); ?></h3> <a><?= $this->t->_($this->exercise['secondaryMuscle']); ?></a></li>
	<li><h3><?= $this->t->_('Mechanics'); ?></h3> <a><?= $this->t->_($this->exercise['mechanics']); ?></a></li>
	<li><h3><?= $this->t->_('Equipment Used'); ?></h3> <a><?= $this->t->_($this->exercise['equipmentUsed']); ?></a></li>
</ul>
	
<h4 class="no-padding"><?= $this->t->_('Instructions'); ?></h4>

	<ul class="field">
		<?php if($this->exercise['instructions']): ?>
		<li>
			<h3><?= $this->t->_('Instructions'); ?></h3>
			<a>
			 <?php 
			    $newstring = $this->exercise['instructions'];
			    $findWhat  = 'Tips';
			    $posUntilTips = strpos($newstring, $findWhat, 1);
		     ?>
		     <?= substr($newstring, 0, $posUntilTips); ?>
			</a>
		</li>
		<li>
			<h3><?= $this->t->_($findWhat); ?></h3>
			<a><?= substr($newstring, $posUntilTips + 5)?></a>
		</li>
		<?php else:?>
		<li>
			<h3><?= $this->t->_('Instructions'); ?></h3>
			<a><?= $this->t->_('No instructions yet'); ?></a>
		</li>
		<?php endif; ?>
	</ul>

<h4 style="padding-bottom:12px;"><?= $this->t->_('Exercise Images lower'); ?></h4>

	    <ul id="gallery" class="gallery" align="center">
	    	
   		<?php foreach($this->exerciseAssets as $image) :
   						echo '<li style="border-top:0px;"><a href="' . $this->assetUrl(array('assetType' => 'picture',
																  'type' 	  => 'full',
			 													  'kind' 	  => strtolower($this->exercise['primaryMuscle']),
			 													  'file' 	  => $image['file'])) . '" 
    							 title="' . $this->exercise['name'] .'">';
	    				
			 			echo '<img alt="' . $this->exercise['name'] . '" src="' . $this->assetUrl(array('assetType' => 'picture',
																  'type' 	  => 'thumb',
			 													  'kind' 	  => strtolower($this->exercise['primaryMuscle']),
			 													  'file' 	  => $image['file'])) . '">';
			 			echo '</a></li>';
					  endforeach; 
				?>
		</ul>
	