<script>
	$(document).ready(function(){
		$("#view-slides").slides({
			effect: 'fade',
			crossfade: true,
			fadeSpeed: 400,
			pause: 10,
			preload: true,
			pagination: true,
			generatePagination: true,
			generateNextPrev: false,		
			play: 4000,
			autoHeight: true
		});
		$("a[rel^='prettyPhoto']").prettyPhoto({
			theme: 'pp_default', // light_rounded / dark_rounded / light_square / dark_square / facebook */
			animation_speed:'normal',
			allow_resize: true,
			keyboard_shortcuts: true,
			show_title: false,
			slideshow:3000,
			social_tools: false,
			autoplay_slideshow: false,
			overlay_gallery: false
		});
	
	});
</script>

<?= $this->partial('_breadcrumbs.phtml', 
				array('t' 		  => $this->t,					  
					  'page'	  => $this->exercise['name'],
					  'pageHref'  => false,
					  'page2'     => $this->exercise['primaryMuscle'],
					  'page2href' => '/index/exercises/type/' . $this->exercise['primaryMuscle']
	)); 
?>

<div id="page">
	
	<div class="row-fluid">
		<div class="span12">
			
			<div class="widget">
				
				<div class="widget-body">					
					<div class="row-fluid">
						<h5><?= $this->t->_('Technical Data'); ?></h5>
						<hr class="clearfix" />
						<div class="span9">						
							<table class="table table-condensed table-hover">
								<thead>
									<tr>
								        <th><?= $this->t->_('Primary Muscle'); ?></th>
								        <th><?= $this->t->_('Secondary Muscle'); ?></th>
								        <th><?= $this->t->_('Mechanics'); ?></th>
								        <th><?= $this->t->_('Equipment Used'); ?></th>								        
								    </tr>
								</thead>
								<tbody>
									<tr>
										<td><?= $this->t->_($this->exercise['primaryMuscle']); ?></td>
						                <td><?= (($this->exercise['secondaryMuscle'] != 'None') ? $this->t->_($this->exercise['secondaryMuscle']) : ''); ?></td>
						                <td><?= $this->t->_($this->exercise['mechanics']); ?></td>
						                <td><?=	$this->t->_($this->exercise['equipmentUsed']); ?></td>
				 					</tr>							
								</tbody>
							</table>
						</div>
					</div>
					
					<div class="row-fluid">
						<h5><?= $this->t->_('Instructions'); ?></h5>
						<hr class="clearfix" />
						<div class="span11">
							<?php if($this->exercise['instructions']): 
								    $newstring = $this->exercise['instructions'];
								    $findWhat  = 'Tips';
								    $posUntilTips = strpos($newstring, $findWhat, 1);
							?>
								    
						    <p><?= substr($newstring, 0, $posUntilTips); ?></p>				    	
						    
						    <h6><?= $this->t->_($findWhat); ?></h6>				    
						    
						    <p><?= substr($newstring, $posUntilTips + 5)?></p>
						    
						    <?php else: 
					    		echo '<p>' . $this->t->_('No instructions yet') . '</p>';
						    	endif; 
						    ?>
						</div>
					</div>
					<div class="row-fluid">
						<h5><?= $this->t->_('Exercise Images'); ?></h5>
						<hr class="clearfix" />
						
						<?php foreach($this->exerciseAssets as $image) : ?>
						<div class="span2">
							<div class="thumbnail">
								<div class="item">
									<?= '<a class="fancybox-button" 
						  					     data-rel="fancybox-button" 
											     href="' . $this->assetUrl(array('assetType'  => 'picture',
																				 'type' 	  => 'full',
																				 'kind' 	  => strtolower($this->exercise['primaryMuscle']),
																				 'file' 	  => $image['file'])) . '"
			    							 title="' . $this->exercise['name'] .'" rel="prettyPhoto[' . $this->exercise['name'] . ']">';
									?>
										<div class="zoom">
											<?= '<img src="' . $this->assetUrl(array('assetType' => 'picture',
																				  	 'type' 	  => 'thumb',
																				  	 'kind' 	  => strtolower($this->exercise['primaryMuscle']),
																				  	 'file' 	  => $image['file'])) . '">';
											?>										
											<div class="zoom-icon"></div>
										</div>
									</a>									
								</div>
							</div>
						</div>
						<?php endforeach; ?>						
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

