<script>
$(document).ready(function(){
	$("#view-slides").slides({
		effect: 'fade',
		crossfade: true,
		fadeSpeed: 400,
		pause: 10,
		preload: true,
		pagination: true,
		generatePagination: true,
		generateNextPrev: false,
		
		play: 4000,
		autoHeight: true
	});
	$("a[rel^='prettyPhoto']").prettyPhoto({
		theme: 'pp_default', // light_rounded / dark_rounded / light_square / dark_square / facebook */
		animation_speed:'normal',
		allow_resize: true,
		keyboard_shortcuts: true,
		show_title: false,
		slideshow:3000,
		social_tools: false,
		autoplay_slideshow: false,
		overlay_gallery: false
	});

});
</script>

<style>
.box-content ul li {
	list-style:none;
}
.pagination {
    padding-left: 65px;
    padding-top: 6px;
    text-align: center;
    width: 100%;
}
.pagination li {
    float: left;
    margin: 0 1px;
}
.pagination li a {
    background-image: url("/images/pagination.png");
    background-position: 0 0;
    display: block;
    float: left;
    height: 0;
    overflow: hidden;
    padding-top: 12px;
    width: 12px;
}
.pagination li.current a {
    background-position: 0 -12px;
}
a.download:hover, a.download:active {
    background-position: 0 -55px;
}
</style>

<section id="maincontainer">
	<div id="main">
	<?php 
		if(!$this->ajax) :
	?>
		<div class="box">
		  <div class="box-header">
		    <h1><?= $this->exercise['name']; ?></h1>
		  </div>
		 </div>
	<?php 
		endif;
	?> 
		 <div class="box">
		   <div class="box-header">
		   <?php 
				if(!$this->ajax) :
		   ?>
				<h1><?= $this->t->_('Exercise Details'); ?></h1>
		   <?php else: ?>
		   		<h1><?= $this->exercise['name']; ?></h1>
		   <?php endif; ?>
		   </div>
				<div class="box-content">
					<table>
					    <thead>
					      <tr>
					        <th><?= $this->t->_('Primary Muscle'); ?></th>
					        <th><?= $this->t->_('Secondary Muscle'); ?></th>
					        <th><?= $this->t->_('Mechanics'); ?></th>
					        <th><?= $this->t->_('Equipment Used'); ?></th>
					      </tr>
					    </thead>
					    <tbody>
					    	<tr>
								<td><?= $this->t->_($this->exercise['primaryMuscle']); ?></td>
				                <td><?= $this->t->_($this->exercise['secondaryMuscle']); ?></td>
				                <td><?= $this->t->_($this->exercise['mechanics']); ?></td>
				                <td><?=	$this->t->_($this->exercise['equipmentUsed']); ?></td>
		 					</tr>
					    </tbody>
					</table>
					
					<br />
					
					<h6><?= $this->t->_('Instructions'); ?></h6>
		    
				    <?php if($this->exercise['instructions']): 
						    $newstring = $this->exercise['instructions'];
						    $findWhat  = 'Tips';
						    $posUntilTips = strpos($newstring, $findWhat, 1);
				    ?>
				    
				    <p><?= substr($newstring, 0, $posUntilTips); ?></p>
				    	
				    <h6><?= $findWhat?></h6>
				    
				    <p><?= substr($newstring, $posUntilTips + 5)?></p>
				    
				    <?php else: 
			    		echo '<p>' . $this->t->_('No instructions yet') . '</p>';
				    endif; ?>
		 			
				</div>
			</div>
			
			 <div class="box grid_3" style="width:228px;">
			   <div class="box-header">
						<h1><?= $this->t->_('Exercise Images'); ?></h1>
			   </div>
			   <div class="box-content">
			   	<div id="view-slider-wrap-slider-wrap">
					    <div id="view-slides" class="slides">
					    	<div class="slides_container">
			   		<?php foreach($this->exerciseAssets as $image) :
	    					echo '<a href="' . $this->assetUrl(array('assetType' => 'picture',
																	  'type' 	  => 'full',
				 													  'kind' 	  => strtolower($this->exercise['primaryMuscle']),
				 													  'file' 	  => $image['file'])) . '" 
	    							 title="' . $this->exercise['name'] .'" rel="prettyPhoto[' . $this->exercise['name'] . ']">';
		    				echo '<div id="slide">'; 
				 			echo '<img src="' . $this->assetUrl(array('assetType' => 'picture',
																	  'type' 	  => 'thumb',
				 													  'kind' 	  => strtolower($this->exercise['primaryMuscle']),
				 													  'file' 	  => $image['file'])) . '">';
				 			echo '</div>';
				 			echo '</a>';
						  endforeach; 
					?>
							</div>
							
					</div>
					
					</div>
			   </div>
			 </div>
		</div>
		
</section>