<!-- calendar/add-daily page -->
<div id="vkNgine-modal-addexercise" class="modal hide fade" tabindex="-1" aria-hidden="true"></div>
<!-- calendar/add-daily page -->

<!-- calendar/view-detail page -->
<div id="vkNgine-modal-viewdetail" class="modal hide fade" tabindex="-1" aria-hidden="true" title="<?= $this->t->_('Daily Workout Details'); ?>"></div>
<!-- calendar/view-detail page -->

<!-- calendar/view-detail page -->
<div id="vkNgine-modal-viewdaydetail" class="modal hide fade" tabindex="-1" aria-hidden="true"></div>
<!-- calendar/view-detail page -->

<!-- calendar/daily-detail page -->
<div id="vkNgine-modal-daydetail" class="modal hide fade" tabindex="-1" aria-hidden="true"></div>
<!-- calendar/daily-detail page -->

<!-- index/addselectedworkouts page -->
<div id="vkNgine-modal-addselectedworkouts" class="modal hide fade" title="<?= $this->t->_('Add exercises to Workouts'); ?>" tabindex="-1" aria-hidden="true"></div>
<!-- index/addselectedworkouts page -->

<!-- my-account/my-workouts pages -->
<div id="vkNgine-modal-editworkout" class="modal hide fade" title="<?= $this->t->_('Edit Workout'); ?>" tabindex="-1" aria-hidden="true"></div>
<div id="vkNgine-modal-manageworkout" class="modal hide fade" title="<?= $this->t->_('Edit Workout'); ?>" tabindex="-1" aria-hidden="true" style="width:600px;"></div>
<div id="vkNgine-modal-exercisedetail" class="modal hide fade" title="<?= $this->t->_('Exercise Detail'); ?>" tabindex="-1" aria-hidden="true"></div>
<div id="vkNgine-modal-deleteworkout" class="modal hide fade" title="<?= $this->t->_('Delete Workout'); ?>" tabindex="-1" aria-hidden="true">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
		<h3><?= $this->t->_('Delete Workout'); ?></h3>
	</div>
	<div class="modal-body">
		<?= $this->t->_('Are you sure you want to delete this workout?'); ?>
	</div>
	<div class="modal-footer">
		<button class="btn" data-dismiss="modal" type="button"><?= $this->t->_('No'); ?></button>
		<button class="btn blue submit" type="button"><?= $this->t->_('Yes'); ?></button>
	</div>	
</div>
<!-- my-account/my-workouts pages -->

<!-- my-account/my-measurements pages -->
<div id="vkNgine-modal-editmeasurement" class="modal hide fade" title="<?= $this->t->_('Edit Measurement'); ?>" tabindex="-1" aria-hidden="true"></div>
<div id="vkNgine-modal-deletemeasurement" class="modal hide fade" title="<?= $this->t->_('Delete Measurement'); ?>" tabindex="-1" aria-hidden="true">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
		<h3><?= $this->t->_('Delete Measurement'); ?></h3>
	</div>
	<div class="modal-body">
		<?= $this->t->_('Are you sure you want to delete this measurement?'); ?>
	</div>
	<div class="modal-footer">
		<button class="btn" data-dismiss="modal" type="button"><?= $this->t->_('No'); ?></button>
		<button class="btn blue submit" type="button"><?= $this->t->_('Yes'); ?></button>
	</div>	
</div>
<!-- my-account/my-measurements pages /-->