<div id="addexercise_dialog" class="modal hide fade addexercise_dialog" tabindex="-1" aria-hidden="true"></div>

<div id="viewDetails-dialog" class="modal hide fade viewDetails-dialog" tabindex="-1" aria-hidden="true" title="<?= $this->t->_('Daily Workout Details'); ?>"></div>

<div class="lnk-viewDayDetails-dialog" style="display:none"></div>
<div class="lnk-dailyDetails-dialog" style="display:none"></div>

<div id="add_selected_workouts_dialog" class="modal hide fade add_selected_workouts_dialog" title="<?= $this->t->_('Add exercises to Workouts'); ?>" tabindex="-1" aria-hidden="true"></div>

<div id="editmeasurements_dialog" class="modal hide fade editmeasurements_dialog" tabindex="-1" aria-hidden="true"></div>

<div id="manageworkout_dialog" class="modal hide fade manageworkout_dialog" title="<?= $this->t->_('Edit Workout'); ?>" tabindex="-1" aria-hidden="true" style="width:600px;"></div>

<div class="btn_exerciseDetail_dialog" title="<?= $this->t->_('Exercise Detail'); ?>" tabindex="-1" aria-hidden="true" style="display:none"></div>

<div id="deleteworkout_dialog" class="modal hide fade" title="<?= $this->t->_('Delete Workout'); ?>" tabindex="-1" aria-hidden="true">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
		<h3 id="myModalLabel3"><?= $this->t->_('Delete Workout'); ?></h3>
	</div>
	<div class="modal-body">
		<?= $this->t->_('Are you sure you want to delete this workout?'); ?>
	</div>
	<div class="modal-footer">
		<button class="btn" data-dismiss="modal" aria-hidden="true"><?= $this->t->_('No'); ?></button>
		<button class="btn btn-primary"><?= $this->t->_('Yes'); ?></button>
	</div>	
</div>

<div id="deletemeasurement_dialog" class="modal hide fade" title="<?= $this->t->_('Delete Measurement'); ?>" tabindex="-1" aria-hidden="true">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
		<h3 id="myModalLabel3"><?= $this->t->_('Delete Measurement'); ?></h3>
	</div>
	<div class="modal-body">
		<?= $this->t->_('Are you sure you want to delete this measurement?'); ?>
	</div>
	<div class="modal-footer">
		<button class="btn" data-dismiss="modal" aria-hidden="true"><?= $this->t->_('No'); ?></button>
		<button class="btn btn-primary"><?= $this->t->_('Yes'); ?></button>
	</div>	
</div>

<div id="editworkout_dialog" class="modal hide fade editworkout_dialog" title="<?= $this->t->_('Edit Workout'); ?>" tabindex="-1" aria-hidden="true"></div>