<div class="lnk-addexercise-dialog" style="display:none"></div>
<div class="lnk-viewDetails-dialog" style="display:none"></div>
<div class="lnk-viewDayDetails-dialog" style="display:none"></div>
<div class="lnk-dailyDetails-dialog" style="display:none"></div>

<div class="btn_add_selected_workouts_dialog" title="<?= $this->t->_('Add exercises to Workouts'); ?>" style="display:none"></div>

<div class="btn_edit_measurements_dialog" title="<?= $this->t->_('Edit Measurement'); ?>" style="display:none"></div>
<div class="btn_manageworkout_dialog" title="<?= $this->t->_('Edit Workout'); ?>" style="display:none"></div>

<div class="btn_exerciseDetail_dialog" title="<?= $this->t->_('Exercise Detail'); ?>" style="display:none"></div>

<div class="btn-deleteworkout-dialog" title="<?= $this->t->_('Delete Workout'); ?>" style="display:none">
	<div class="dialog-content">
		<?= $this->t->_('Are you sure you want to delete this workout?'); ?>
	</div>
</div>

<div class="btn_deletemeasurement-dialog" title="<?= $this->t->_('Delete Measurement'); ?>" style="display:none">
	<div class="dialog-content">
		<?= $this->t->_('Are you sure you want to delete this measurement?'); ?>
	</div>
</div>


<div id="edit_workout_dialog" class="modal hide fade btn_edit_workout_dialog" title="<?= $this->t->_('Edit Workout'); ?>" tabindex="-1" role="dialog" aria-labelledby="btn_edit_workout_dialog" aria-hidden="true">
	
</div>