<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
	<h3 id="myModalLabel3"><?= $this->t->_('Edit Workout'); ?></h3>
</div>
<div class="modal-body">
	<?= $this->content; ?>
</div>
<div class="modal-footer">
	<button class="btn" data-dismiss="modal" aria-hidden="true"><?= $this->t->_('Cancel'); ?></button>
	<button class="btn btn-primary"><?= $this->t->_('Save'); ?></button>
</div>