<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
	<h3><?= $this->t->_($this->headline); ?></h3>
</div>
<div class="modal-body">
	<?= $this->content; ?>
</div>
<div class="modal-footer">
	<button class="btn" data-dismiss="modal" type="button"><?= $this->t->_('Cancel'); ?></button>
	<button class="btn blue submit" type="button"><?= $this->t->_('Save'); ?></button>
</div>