<div class="header navbar navbar-inverse navbar-fixed-top">	
	<div class="navbar-inner">
		<div class="container-fluid">
			<a class="brand" href="<?= $this->publicUrl(); ?>">
				<img src="/dumbbell.png" alt="<?= $this->t->_('GYM Tracker'); ?>" width="40"/>
			</a>
		
			<a href="javascript:;" class="btn-navbar collapsed" data-toggle="collapse" data-target=".nav-collapse">
				<img src="/images/menu-toggler.png" alt="" />
			</a>  
		
		<ul class="nav pull-right">
			<li class="dropdown">
				<?php 
			    $language = new Zend_Session_Namespace('language');
			    
			    if($language->__isset('session')){
			        $lang = $language->lang;
			    }
			    else{
			        $lang = vkNgine_Config::getSystemConfig()->language->locale;
			    }
			    
			    if($lang == 'tr') {
					$label = 'TR';
				}
				else {
					$label = 'US';
				}
			    ?>
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true" data-lang="<?= $lang; ?>">
                	<img alt="" src="/images/<?= $lang; ?>.png" width="17" height="11" />
                	<span class="username"><?= $label; ?></span>
                	<i class="icon-angle-down"></i>
                </a>
                <ul class="dropdown-menu">
                    <li>
                    	<a href="#" class="language" data-lang="tr"><img alt="" src="/images/tr.png" width="20" height="11" /> <?= $this->t->_('Turkish'); ?></a>
                    	<a href="#" class="language" data-lang="en"><img alt="" src="/images/en.png" width="20" height="11" /> <?= $this->t->_('English'); ?></a>
                    </li>
            	</ul>
			</li>
			<li class="dropdown user">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">
					<img alt="" src="/images/avatar1_small.jpg" />
					<span class="username"><?= $this->user->getFullName(); ?></span>
					<i class="icon-angle-down"></i>
				</a>
				<ul class="dropdown-menu">
					<?php
						$calendarLink = ('weekly' == strtolower($this->user->calendarView)) ? '/calendar/weekly' : '/calendar';
						$calorieCalendarLink = ('weekly' == strtolower($this->user->calendarView)) ? '/calorie-calendar/weekly' : '/calorie-calendar';
					?>
					<li><a href="/my-account"><i class="icon-user"></i> <?= $this->t->_('My Account'); ?></a></li>
					<li><a href="<?= $calendarLink; ?>"><i class="icon-calendar"></i> <?= $this->t->_('Exercise Calendar'); ?></a></li>
					<li><a href="<?= $calorieCalendarLink; ?>"><i class="icon-calendar"></i> <?= $this->t->_('Calorie Calendar'); ?></a></li>
					<li class="divider"></li>
					<li><a href="/auth/login/logout"><i class="icon-key"></i> <?= $this->t->_('Log Out'); ?></a></li>
				</ul>
			</li>
				</ul>
				
		</div>
		</div>
	</div>