<?php
define('IN_DEVELOPMENT', APPLICATION_ENV === 'development');

echo $this->doctype() . "\n";

$this->headLink()
		->prependStylesheet($this->baseUrl('/css/mobile/style.css'));
		
$this->headMeta()
		->appendHttpEquiv('Content-Type', 'text/html; charset=UTF-8')
		->appendHttpEquiv('expires', 'Oct, 31 Sun 1982 06:66:66 GMT')
		->appendName('apple-mobile-web-app-capable', 'yes')
		->appendName('apple-mobile-web-app-status-bar-style', 'black')
		->appendName('viewport', 'user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0');
?>

<html xmlns="http://www.w3.org/1999/xhtml">
<head>

<?= $this->headTitle() . "\n"; ?>

<?= $this->headMeta() . "\n"; ?>
	
<?= $this->headLink()  . "\n"; ?>

</head>

<body>
	<?= $this->layout()->content ?>
</body>
</html>