<?php
define('IN_DEVELOPMENT', APPLICATION_ENV === 'development');

echo $this->doctype() . "\n";

$this->headLink()
		->prependStylesheet($this->baseUrl('/js/public/bootstrap/css/bootstrap.min.css'))
		->appendStylesheet($this->baseUrl('/js/public/bootstrap/css/bootstrap-responsive.min.css'))
		->appendStylesheet($this->baseUrl('/css/font-awesome/css/font-awesome.css'))
		->appendStylesheet($this->baseUrl('/css/style-metro.css'))
		->appendStylesheet($this->baseUrl('/css/style.css'))		
		->appendStylesheet($this->baseUrl('/css/style-responsive.css'))
	 	->appendStylesheet($this->baseUrl('/css/themes/default.css'), '', true, array('id' => 'style_color'))
		->appendStylesheet($this->baseUrl('/js/public/uniform/css/uniform.default.css'))
		->appendStylesheet($this->baseUrl('/js/public/gritter/css/jquery.gritter.css'))		
		->appendStylesheet($this->baseUrl('/js/public/bootstrap-datepicker/css/datepicker.css'))
		->appendStylesheet($this->baseUrl('/js/public/bootstrap-daterangepicker/daterangepicker.css'))
		->appendStylesheet($this->baseUrl('/js/public/bootstrap-datetimepicker/css/datetimepicker.css'))
		->appendStylesheet($this->baseUrl('/js/public/fullcalendar/fullcalendar.css'))
		->appendStylesheet($this->baseUrl('/js/public/jqvmap/jqvmap/jqvmap.css'))
		->appendStylesheet($this->baseUrl('/js/public/jquery-easy-pie-chart/jquery.easy-pie-chart.css'))
 		->appendStylesheet($this->baseUrl('/css/glyphicons/css/glyphicons.css'))
 		->appendStylesheet($this->baseUrl('/js/public/bootstrap-modal/css/bootstrap-modal.css'))
		->headLink(array('rel' => 'icon', 'href' => $this->baseUrl('dumbbell.ico'), 'type' => 'image/x-icon', 'PREPEND'));

$this->headScript()
	     ->prependFile($this->baseUrl('/js/public/jquery-1.10.1.min.js'))
	     ->appendFile($this->baseUrl('/js/public/jquery-migrate-1.2.1.min.js'))
	     ->appendFile($this->baseUrl('/js/public/jquery-ui/jquery-ui-1.10.1.custom.min.js'))	    
	     ->appendFile($this->baseUrl('/js/public/bootstrap/js/bootstrap.min.js'))
	     ->appendFile($this->baseUrl('/js/public/excanvas.min.js'), 'text/javascript', array('conditional' => 'lt IE 9'))
	     ->appendFile($this->baseUrl('/js/public/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9'))
	     ->appendFile($this->baseUrl('/js/public/jquery-slimscroll/jquery.slimscroll.min.js'))
	     ->appendFile($this->baseUrl('/js/public/bsn.AutoSuggest_2.1.3_comp.js'))
	     ->appendFile($this->baseUrl('/js/public/jquery.blockui.min.js'))
	     ->appendFile($this->baseUrl('/js/public/jquery.cookie.min.js'))
	     ->appendFile($this->baseUrl('/js/public/uniform/jquery.uniform.min.js'))	 
	     ->appendFile($this->baseUrl('/js/public/bootstrap-datepicker/js/bootstrap-datepicker.js'))
	     ->appendFile($this->baseUrl('/js/public/bootstrap-datetimepicker/js/bootstrap-datetimepicker.js'))
	     ->appendFile($this->baseUrl('/js/public/bootstrap-daterangepicker/date.js'))
	     ->appendFile($this->baseUrl('/js/public/bootstrap-daterangepicker/daterangepicker.js'))	  
	     ->appendFile($this->baseUrl('/js/public/bootstrap-modal/js/bootstrap-modal.js'))
	     ->appendFile($this->baseUrl('/js/public/bootstrap-modal/js/bootstrap-modalmanager.js'))
	     ->appendFile($this->baseUrl('/js/public/gritter/js/jquery.gritter.js'))		 
		 ->appendFile($this->baseUrl('/js/public/uniform/jquery.uniform.min.js'))
		 ->appendFile($this->baseUrl('/js/public/fullcalendar/fullcalendar.min.js'))
		 ->appendFile($this->baseUrl('/js/public/jquery-easy-pie-chart/jquery.easy-pie-chart.js'))
		 ->appendFile($this->baseUrl('/js/public/jquery.sparkline.min.js'))		 
		 ->appendFile($this->baseUrl('/js/public/dialog.js'))
		 ->appendFile($this->baseUrl('/js/form.js'))
		 ->appendFile($this->baseUrl('/js/public/scripts/app.js'))
		 ->appendFile($this->baseUrl('/js/public/scripts/index.js'))
		 ->appendFile($this->baseUrl('/js/public/scripts/form-components.js'))
		 ->appendFile($this->baseUrl('/js/public/vkNgine.js'));
		 	 	
$this->headMeta()
     	->appendHttpEquiv('Content-Type', 'text/html; charset=UTF-8')
		->appendHttpEquiv('expires', 'Oct, 31 Sun 1982 06:66:66 GMT')
		->appendHttpEquiv('pragma', 'no-cache')
		->appendHttpEquiv('Cache-Control', 'no-cache')
		->appendName('viewport', 'width=device-width, initial-scale=1.0');

$language = new Zend_Session_Namespace('language');
 
$lang = null;
if($language->__isset('session')){
	$lang = $language->lang;
}

if('tr' == vkNgine_Config::getSystemConfig()->language->locale || 'tr' == $lang) {
	$this->headScript()->appendFile($this->baseUrl('/js/admin/ui/locale/ui.datepicker-tr.js'));
}

?>

<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if IE 10]> <html lang="en" class="ie10 no-js"> <![endif]-->
<!--[if !IE]><!--> <html lang="en" class="no-js"> <!--<![endif]-->
<!-- BEGIN HEAD -->

<head>
<?= $this->headTitle() . "\n"; ?>
<?= $this->headMeta() . "\n"; ?>	
<?= $this->headLink()  . "\n"; ?>
<?= $this->headScript(). "\n"; ?>
</head>
		
<body class="page-header-fixed" vkNgine_version="<?= vkNgine_Version::VERSION; ?>" >

	<?= $this->partial('layout_header.phtml', 
						array('user' => $this->user,
						      't'    => $this->t,
		));
 	?>
	
	<div class="page-container">
		
		<?= $this->partial('layout_nav.phtml',
							array('user' 		=> $this->user,
						      	  't'    		=> $this->t,	
								  'params'  	=> $this->params,
								  'exercises' 	=> $this->exercises, 
			));
		?>
			
		<div class="page-content">
			<div class="container-fluid">
	      	 	<?php echo $this->layout()->content; ?>
			</div>
		</div>
	</div>
	</div>
		
	<div class="footer">
		<div class="footer-inner">
			<?= date('Y'); ?> &copy; <img src="/images/admin/vkn_v2_powered_by.png">
		</div>
		<div class="footer-tools">
			<span class="go-top">
				<i class="icon-angle-up"></i>
			</span>
		</div>
	</div>
	
	</div>
	
  	<script>
		jQuery(document).ready(function() {    
		   App.init(); // initlayout and core plugins
		   Index.init();
		   Index.initCharts(); // init index page's custom scripts
		   Index.initChat();
		   Index.initMiniCharts();
		   Index.initDashboardDaterange();
		   Index.initIntro();
		   FormComponents.init();
		   
		});
	</script>
    
    <?php if(vkNgine_Config::getSystemConfig()->settings->ga->enabled) : ?>	
	<script type="text/javascript">
	  var _gaq = _gaq || [];
	  _gaq.push(['_setAccount', '<?= vkNgine_Config::getSystemConfig()->settings->ga->code; ?>']);
	  _gaq.push(['_trackPageview']);
	
	  (function() {
	    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
	    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
	    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	  })();
	</script>
	<?php endif; ?>
	
	<?= $this->partial('_dialog.phtml', array('t' => $this->t)); ?>

</body>
</html>	