<?php

define('IN_DEVELOPMENT', APPLICATION_ENV === 'development');

echo $this->doctype() . "\n";

$this->headLink()
		->prependStylesheet($this->baseUrl('/js/public/bootstrap/css/bootstrap.min.css'))
		->headLink(array('rel' => 'icon', 'href' => $this->baseUrl('dumbbell.ico'), 'type' => 'image/x-icon', 'PREPEND'))
		->appendStylesheet($this->baseUrl('/js/public/bootstrap/css/bootstrap-responsive.min.css'))
		->appendStylesheet($this->baseUrl('/css/font-awesome/css/font-awesome.css'))
		->appendStylesheet($this->baseUrl('/css/styles.css'))
		->appendStylesheet($this->baseUrl('/css/style_responsive.css'))
	 	->appendStylesheet($this->baseUrl('/css/style_default.css'), 'screen', true, array('id' => 'style_color'))
	 	->appendStylesheet($this->baseUrl('#'), '', true, array('id' => 'style_metro'))
	 	->appendStylesheet($this->baseUrl('/css/vkNgine-calendar.css'))
		->appendStylesheet($this->baseUrl('/css/gritter/css/jquery.gritter.css'))
		->appendStylesheet($this->baseUrl('/css/uniform/css/uniform.default.css'))
		->appendStylesheet($this->baseUrl('/js/public/bootstrap-daterangepicker/daterangepicker.css'))		
		->appendStylesheet($this->baseUrl('/js/public/fullcalendar/bootstrap-fullcalendar.css'))
		->appendStylesheet($this->baseUrl('/css/data-tables/DT_bootstrap.css'));

$this->headScript()
	     ->prependFile($this->baseUrl('/js/jquery-1.8.2.min.js'))
	     ->appendFile($this->baseUrl('/js/jquery-ui-1.9.2.custom.min.js'))
	     ->appendFile($this->baseUrl('/js/public/slimScroll/slimScroll.min.js'))	     
	     ->appendFile($this->baseUrl('/js/public/fullcalendar/fullcalendar.min.js'))
	     ->appendFile($this->baseUrl('/js/form.js'))	     
	     ->appendFile($this->baseUrl('/js/public/bootstrap/js/bootstrap.min.js'))
	     ->appendFile($this->baseUrl('/js/public/bsn.AutoSuggest_2.1.3_comp.js'))
	     ->appendFile($this->baseUrl('/js/public/jquery.blockui.js'))
	     ->appendFile($this->baseUrl('/js/admin/gritter.js'))
	     ->appendFile($this->baseUrl('/js/public/jquery.cookie.js'))
	     ->appendFile($this->baseUrl('/js/public/jquery.knob.js'))
	     ->appendFile($this->baseUrl('/js/public/bootstrap-daterangepicker/date.js'))
	     ->appendFile($this->baseUrl('/js/public/bootstrap-daterangepicker/daterangepicker.js'))
	     ->appendFile($this->baseUrl('/js/public/html5.js'), 'text/javascript', array('conditional' => 'lt IE 9'))
	     ->appendFile($this->baseUrl('/js/public/excanvas.js'), 'text/javascript', array('conditional' => 'lt IE 9'))
		 ->appendFile($this->baseUrl('/js/public/respond.js'), 'text/javascript', array('conditional' => 'lt IE 9'))
		 ->appendFile($this->baseUrl('/js/gritter/js/jquery.gritter.js'))
		 ->appendFile($this->baseUrl('/css/uniform/jquery.uniform.min.js'))
		 ->appendFile($this->baseUrl('/css/data-tables/jquery.dataTables.js'))
		 ->appendFile($this->baseUrl('/css/data-tables/DT_bootstrap.js'))
		 ->appendFile($this->baseUrl('/js/public/vkNgine.js'));
		 	 	
$this->headMeta()
		->appendHttpEquiv('Content-Type', 'text/html; charset=UTF-8')
		->appendHttpEquiv('expires', 'Oct, 31 Sun 1982 06:66:66 GMT')
		->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
		->appendName('apple-mobile-web-app-capable', 'yes')
		->appendName('apple-mobile-web-app-status-bar-style', 'black')
		->appendName('viewport', 'width=1024px, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no');

if('tr' == vkNgine_Config::getSystemConfig()->language->locale) {
	$this->headScript()->appendFile($this->baseUrl('/js/admin/ui/locale/ui.datepicker-tr.js'));
}

?>

<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->
<!--[if IE 10]> <html lang="en" class="ie10"> <![endif]-->
<!--[if !IE]><!--> <html lang="en"> <!--<![endif]-->
<!-- BEGIN HEAD -->

<head>
<?= $this->headTitle() . "\n"; ?>
<?= $this->headMeta() . "\n"; ?>	
<?= $this->headLink()  . "\n"; ?>
<?= $this->headScript(). "\n"; ?>
</head>
		
<body class="fixed-top" vkNgine_version="<?= vkNgine_Version::VERSION; ?>" >

	<?= $this->partial('layout_header.phtml', 
						array('user' => $this->user,
						      't'    => $this->t,
		));
 	?>
	
	<div id="container" class="row-fluid">
		
		<?= $this->partial('layout_nav.phtml',
							array('user' 		=> $this->user,
						      	  't'    		=> $this->t,	
								  'params'  	=> $this->params,
								  'exercises' 	=> $this->exercises, 
			));
		?>
		
		<div id="body">
			<div class="container-fluid">
	      	 	<?php echo $this->layout()->content; ?>
			</div>
		</div>
	</div>	
		
	<div id="footer" class="center">
			<?= date('Y'); ?> &copy; <img src="/images/admin/vkn_v2_powered_by.png">
		<div class="span pull-right">
			<span class="go-top"><i class="icon-arrow-up"></i></span>
		</div>
	</div>
	
  	<script>
	jQuery(document).ready(function() {
	 	vkNgine.setMainPage(true);
		vkNgine.init();
	});
	</script>
    
    <?php if(vkNgine_Config::getSystemConfig()->settings->ga->enabled) : ?>	
	<script type="text/javascript">
	  var _gaq = _gaq || [];
	  _gaq.push(['_setAccount', '<?= vkNgine_Config::getSystemConfig()->settings->ga->code; ?>']);
	  _gaq.push(['_trackPageview']);
	
	  (function() {
	    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
	    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
	    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	  })();
	</script>
	<?php endif; ?>
	
	<?= $this->partial('_dialog.phtml', array('t' => $this->t)); ?>

</body>
</html>	