<div class="header navbar navbar-inverse navbar-fixed-top">	
	<div class="navbar-inner">
		<div class="container-fluid">
			<a class="brand" href="<?= $this->publicUrl(); ?>">
				<img src="/dumbbell.png" alt="<?= $this->t->_('GYM Tracker'); ?>" width="40"/>
			</a>
		
			<a href="javascript:;" class="btn-navbar collapsed" data-toggle="collapse" data-target=".nav-collapse">
				<img src="/images/menu-toggler.png" alt="" />
			</a>  
		
		<ul class="nav pull-right">
			<li class="dropdown" id="header_task_bar">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">
				<i class="icon-tasks"></i>
				<span class="badge">5</span>
				</a>
				<ul class="dropdown-menu extended tasks">
					<li>
						<p>You have 12 pending tasks</p>
					</li>
					<li>
						<a href="#">
						<span class="task">
						<span class="desc">New release v1.2</span>
						<span class="percent">30%</span>
						</span>
						<span class="progress progress-success ">
						<span style="width: 30%;" class="bar"></span>
						</span>
						</a>
					</li>
					<li>
						<a href="#">
						<span class="task">
						<span class="desc">Application deployment</span>
						<span class="percent">65%</span>
						</span>
						<span class="progress progress-danger progress-striped active">
						<span style="width: 65%;" class="bar"></span>
						</span>
						</a>
					</li>
					<li>
						<a href="#">
						<span class="task">
						<span class="desc">Mobile app release</span>
						<span class="percent">98%</span>
						</span>
						<span class="progress progress-success">
						<span style="width: 98%;" class="bar"></span>
						</span>
						</a>
					</li>
					<li>
						<a href="#">
						<span class="task">
						<span class="desc">Database migration</span>
						<span class="percent">10%</span>
						</span>
						<span class="progress progress-warning progress-striped">
						<span style="width: 10%;" class="bar"></span>
						</span>
						</a>
					</li>
					<li>
						<a href="#">
						<span class="task">
						<span class="desc">Web server upgrade</span>
						<span class="percent">58%</span>
						</span>
						<span class="progress progress-info">
						<span style="width: 58%;" class="bar"></span>
						</span>
						</a>
					</li>
					<li>
						<a href="#">
						<span class="task">
						<span class="desc">Mobile development</span>
						<span class="percent">85%</span>
						</span>
						<span class="progress progress-success">
						<span style="width: 85%;" class="bar"></span>
						</span>
						</a>
					</li>
					<li class="external">
						<a href="#">See all tasks <i class="m-icon-swapright"></i></a>
					</li>
				</ul>
			</li>				
			<li class="dropdown">
				<?php 
			    $options = vkNgine_Config::getSystemConfig();
			    
			    $language = new Zend_Session_Namespace('language');
			    
			    if($language->__isset('session')){
			        $lang = $language->lang;
			    }
			    else{
			        $lang = $options['language']['locale'];
			    }
			    
			    if($lang == 'tr') {
					$label = 'TR';
				}
				else {
					$label = 'US';
				}
			    ?>
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true" data-lang="<?= $lang; ?>">
                	<img alt="" src="/images/<?= $lang; ?>.png" width="17" height="11" />
                	<span class="username"><?= $label; ?></span>
                	<i class="icon-angle-down"></i>
                </a>
                <ul class="dropdown-menu">
                    <li>
                    	<a href="#" class="language" data-lang="tr"><img alt="" src="/images/tr.png" width="20" height="11" /> <?= $this->t->_('Turkish'); ?></a>
                    	<a href="#" class="language" data-lang="en"><img alt="" src="/images/en.png" width="20" height="11" /> <?= $this->t->_('English'); ?></a>
                    </li>
            	</ul>
			</li>
			<li class="dropdown user">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">
					<img alt="" src="/images/avatar1_small.jpg" />
					<span class="username"><?= $this->user->getFullName(); ?></span>
					<i class="icon-angle-down"></i>
				</a>
				<ul class="dropdown-menu">
					<?php
						$calendarLink = ('weekly' == strtolower($this->user->calendarView)) ? $this->publicUrl('weekly', 'calendar') : $this->publicUrl(null, 'calendar');
						$calorieCalendarLink = ('weekly' == strtolower($this->user->calendarView)) ? $this->publicUrl('weekly', 'calorie-calendar') : $this->publicUrl(null, 'calorie-calendar');
					?>
					<li><a href="<?= $this->publicUrl(null, 'my-account'); ?>"><i class="icon-user"></i> <?= $this->t->_('My Account'); ?></a></li>
					<li><a href="<?= $calendarLink; ?>"><i class="icon-calendar"></i> <?= $this->t->_('Exercise Calendar'); ?></a></li>
					<li><a href="<?= $calorieCalendarLink; ?>"><i class="icon-calendar"></i> <?= $this->t->_('Calorie Calendar'); ?></a></li>
					<li class="divider"></li>
					<li><a href="/auth/login/logout"><i class="icon-key"></i> <?= $this->t->_('Log Out'); ?></a></li>
				</ul>
			</li>
				</ul>
				
		</div>
		</div>
	</div>