	<td rel="<?= $this->date; ?>" class="<?= $this->class; ?> fc-widget-content <?= $this->firstLast; ?>">	
		<div>
			<div class="fc-day-number"><?= $this->day->thisDay(); ?></div>
			<div class="fc-day-content">
<?php
if(0 < count($this->macros[$this->date])) :
?>
				<div style="position:relative">
					<div class="fc-event fc-event-skin fc-event-hori fc-corner-left fc-corner-right" style="background-color: rgb(71, 125, 174); border-color: rgb(14, 105, 161); top: 30px; -moz-user-select: none;">
						<div class="fc-event-inner fc-event-skin" style="background-color:#477dae;border-color:#0E69A1">
							<span class="fc-event-time"><?= sprintf($this->t->_('%s Calorie consumed'), $this->macros[$this->date]['totalCalories']); ?></span>
						</div>
					</div>
				</div>
<?php endif; ?>
			</div>
		</div>
	</td>
