<td rel=<?= $this->date; ?> class="fc-widget-content addExercise <?= $this->highlightedCss; ?> <?= $this->firstLast; ?> " style="width:100px">
	<div style="height: 200px;">
		<div class="fc-day-content">
			<div style="position: relative">	
	<?php 
	if(0 < count($this->macros[$this->date])) :
	?>
				<div class="fc-event fc-event-skin fc-event-hori fc-corner-left fc-corner-right" style="background-color: rgb(71, 125, 174); border-color: rgb(14, 105, 161); top: 30px; -moz-user-select: none;">
					<div class="fc-event-inner fc-event-skin" style="background-color: #477dae; border-color: #0E69A1; color: #000000">
						<span class="fc-event-time"><strong><?= $this->t->_('Daily Consumption'); ?></strong></span>
						<span class="fc-event-title"> <br /> 			
							<?= (sprintf($this->t->_('%s calories'), $this->macros[$this->date]['macros']['calories'])); ?> <br />
							<?= (sprintf($this->t->_('%s gr protein'), $this->macros[$this->date]['macros']['protein'])); ?> <br />
							<?= (sprintf($this->t->_('%s gr cholesterol'), $this->macros[$this->date]['macros']['cholesterol'])); ?> <br />
							<?= (sprintf($this->t->_('%s gr fat'), $this->macros[$this->date]['macros']['fat'])); ?> <br /> 
							<?= (sprintf($this->t->_('%s gr carbs'), $this->macros[$this->date]['macros']['carbs'])); ?> <br />
							<?= (sprintf($this->t->_('%s gr sugar'), $this->macros[$this->date]['macros']['sugar'])); ?> <br />
							<?= (sprintf($this->t->_('%s gr fiber'), $this->macros[$this->date]['macros']['fiber']));  ?> 
						 </span>
					</div>
				</div>
	<?php endif; ?>
			</div>
		</div>
	</div>
</td>