<?php 
$state = null;
if(isset($this->params['day'])) {
	if (date('d') == $this->params['day']){
		$state = 'fc-state-disabled';
	}
}

$this->calendar->build();
$prevWeek = $this->calendar->prevWeek('array');
$nextWeek = $this->calendar->nextWeek('array');

$today =  '/calorie-calendar/weekly/';
$prev = '/calorie-calendar/weekly/year/' . $prevWeek['year'] . '/month/' . $prevWeek['month'] . '/day/' . $prevWeek['day'];
$next = '/calorie-calendar/weekly/year/' . $nextWeek['year'] . '/month/' . $nextWeek['month'] . '/day/' . $nextWeek['day'];

?>

<script>
	$(function() {
		$('.fc-button-prev').bind('click', function() {
			window.top.location = '<?= $prev; ?>';
		});
		$('.fc-button-next').bind('click', function() {
			window.top.location = '<?= $next; ?>';
		});
		$('.fc-button-today').bind('click', function() {
			window.top.location = '<?= $today; ?>';
		});
		$('.fc-button-month').bind('click', function() {
			window.top.location = '<?= $this->publicUrl('monthly', 'calorie-calendar'); ?>';
		});
		$('.fc-button-agendaWeek').bind('click', function() {
			window.top.location = '<?= $this->publicUrl('weekly', 'calorie-calendar'); ?>';
		});

		<?php
			if(!isset($this->params['month'])) :
		?>
			$('.fc-button-today').addClass('fc-state-disabled');
		<?php endif; ?>
	});	
</script>

<?= $this->partial('_breadcrumbs.phtml', 
				array('t' 		  => $this->t,
					  'pageTitle' => null,
					  'page'	  => $this->t->_('Weekly Calendar'),
					  'page2'     => $this->t->_('Calorie Calendar'),
					  'page2href' => '',
	)); 
?>

<div class="row-fluid">
	<div class="span12">			
		<div class="portlet box blue calendar">
			<div class="portlet-title">
				<div class="caption">
					<i class="icon-calendar"></i>
					<span class="hidden-480">
					<?php
						echo
						$this->partial('calendar/_calendarHeader.phtml',
								array('t'        => $this->t,
									  'mode'     => 'weekly',
									  'calendar' => $this->calendar
								));
			    	?>
					</span>
				</div> 							
			</div>
		<div class="portlet-body light-grey">
			<div class="row-fluid">
				<div id="calendar" class="has-toolbar">
					<table class="fc-header" style="width: 100%;">
						<tbody>
							<tr>
								<td class="fc-header-left"></td>
								<td class="fc-header-center"></td>
								<td class="fc-header-right">
									<span class="fc-button fc-button-prev fc-state-default fc-corner-left" unselectable="on"><span class="fc-text-arrow">&lt;</span></span><span class="fc-button fc-button-next fc-state-default" unselectable="on"><span class="fc-text-arrow">&gt;</span></span><span class="fc-button fc-button-today fc-state-default <?= $state; ?>" unselectable="on"><?= $this->t->_('today'); ?></span><span class="fc-button fc-button-month fc-state-default" unselectable="on"><?= $this->t->_('month'); ?></span><span class="fc-button fc-button-agendaWeek fc-state-active fc-state-default" unselectable="on"><?= $this->t->_('week'); ?></span>
							</tr>
						</tbody>
					</table>
					<div class="fc-content" style="position: relative; min-height: 1px;">
						<div class="fc-view fc-view-agendaWeek fc-agenda" style="position: relative; -moz-user-select: none; display: block;" unselectable="on">
							<table class="fc-agenda-days fc-border-separate" cellspacing="0" style="width:100%">
								<thead>
									<tr class="fc-first fc-last">
										<?php 
									    	$this->calendar->build();
									    	
									    	echo
									    	$this->partial('calendar/_weeklyHeader.phtml',
									    			array('t'        => $this->t,
									    				  'calendar' => $this->calendar
									    			));
									    ?>
									</tr>
								</thead>
								<tbody>
									<tr class="fc-first fc-last">
										<?php
											while ($day = $this->calendar->fetch()) {
												$modelDailyIntake = new Public_Model_Daily_Intake();
												
												$thisMonth = ((strlen($day->thisMonth()) == 1) ? '0'. $day->thisMonth() : $day->thisMonth());
												$thisDay = ((strlen($day->thisDay()) == 1) ? '0'. $day->thisDay() : $day->thisDay());
																		
												$date = $day->thisYear() . '-' . $thisMonth . '-' . $thisDay;	
												
												$macros = $modelDailyIntake->fetchMacros($date, $this->user);
												
												$highlightedCss = null;
												$highlightedCss = ($date == date('Y-m-d')) ? 'fc-state-highlight' : '';
												
												$firstLast = null;
												
												if(date('D', $day->thisDay(true)) == 'Mon'){
													$firstLast = 'fc-first';
												}
												if(date('D', $day->thisDay(true)) == 'Sun'){
													$firstLast = 'fc-last';
												}
									
												echo 
												    $this->partial('calorie-calendar/_renderDayWeekly.phtml',
														array('t'              => $this->t,
															  'date'   	       => $date,
															  'macros' 		   => $macros,
														      'firstLast'      => $firstLast,
															  'highlightedCss' => $highlightedCss,
													));
						    				}
					    				?>
									</tr>
								</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
</div>
</div>