<div id="btn-logout-dialog" title="<?= $this->t->_('Exiting from Admin Panel'); ?>" style="display:none">
	<p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>
	<?= $this->t->_('Are you sure you want to logout from the Administrator Panel?'); ?></p>
</div>

<div id="btn-myaccount-dialog" title="<?= $this->t->_('Account Settings are being changed'); ?>" style="display:none"></div>
<div id="btn-edituser-dialog" style="display:none"></div>
<div id="btn-editexercise-dialog" style="display:none"></div>
<div id="btn-editworkout-dialog" style="display:none"></div>
<div id="btn-editmeal-dialog" style="display:none"></div>
<div id="btn-editfood-dialog" style="display:none"></div>
<div id="btn-addexercisetoworkout-dialog" style="display:none"></div>
<div id="btn-addfoodstomeals-dialog" style="display:none"></div>

<div id="btn-deleteuser-dialog" title="<?= $this->t->_('User is being deleted'); ?>" style="display:none">
	<p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>
	<?= $this->t->_('Are you sure you want to delete this user?'); ?></p>
</div>

<div id="btn-deletemeal-dialog" title="<?= $this->t->_('Meal is being deleted'); ?>" style="display:none">
	<p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>
	<?= $this->t->_('Are you sure you want to delete this meal?'); ?></p>
</div>

<div id="btn-deletefood-dialog" title="<?= $this->t->_('Food is being deleted'); ?>" style="display:none">
	<p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>
	<?= $this->t->_('Are you sure you want to delete this food?'); ?></p>
</div>

<div id="btn-deleteexercise-dialog" title="<?= $this->t->_('Exercise is being deleted'); ?>" style="display:none">
	<p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>
	<?= $this->t->_('Are you sure you want to delete this exercise?'); ?></p>
</div>

<div id="btn-deleteworkout-dialog" title="<?= $this->t->_('Exercise is being deleted'); ?>" style="display:none">
	<p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>
	<?= $this->t->_('Are you sure you want to delete this workout?'); ?></p>
</div>

<div id="btn-deletelist-dialog" title="<?= $this->t->_('Selected items are being deleted'); ?>" style="display:none">
	<p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>
	<?= $this->t->_('Are you sure you want to delete these items?'); ?></p>
</div>

<div id="btn-cacheclear-dialog" title="<?= $this->t->_('Cache database will be truncated'); ?>" style="display:none">
	<p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>
	<?= $this->t->_('Are you sure you want to clear the cache?'); ?></p>
</div>

<div id="lnk-showdetails-dialog" style="display:none"></div>