<script type="text/javascript">
$(document).ready(function() {
	$('.checkOne').bind('click', function() {
		var count;
		count = countCheckedCheckboxes('input');
										
		if(count > 0) {
			$('.deleteSelected').removeClass('ui-state-disabled');
		}
		else {
			$('.deleteSelected').addClass('ui-state-disabled');
		}
	});	
});

var checkflag = "false";
function check(field, allSelected, selectAll) {
	if (checkflag == "false") {
		for (i = 0; i < field.length; i++) {
			field[i].checked = true;
		}
		checkflag = "true";

		$('.selectAll').html(allSelected);
		$('.deleteSelected').removeClass('ui-state-disabled');
	}
	else {
		for (i = 0; i < field.length; i++) {
			field[i].checked = false; 
		}
		checkflag = "false";	
		
		$('.selectAll').html(selectAll);
		$('.deleteSelected').addClass('ui-state-disabled');
	}
}

function countCheckedCheckboxes(name) 
{
	total = $('' + name + ':checked').map(function(i,n) {
    	return $(n).val();
    }).get();
	
	return total.length;
}
</script>

