<?php

define('IN_DEVELOPMENT', APPLICATION_ENV === 'development');

echo $this->doctype() . "\n";

$this->headLink()
		->prependStylesheet($this->baseUrl('/css/mobile/style.css'))
		->appendStylesheet($this->baseUrl('/css/mobile/buttons.css'))
		->appendStylesheet($this->baseUrl('/css/mobile/type.css'))
		->headLink(array('rel' => 'apple-touch-icon', 'href' => '/dumbbell.png'))
		->appendStylesheet($this->baseUrl('/css/mobile/photoswipe.css'));
	 
$this->headScript()
	     ->prependFile($this->baseUrl('/js/jquery-1.7.1.js'))
	     ->appendFile($this->baseUrl('/js/form.js'))
	     ->appendFile($this->baseUrl('/js/mobile/klass.min.js'))
		 ->appendFile($this->baseUrl('/js/mobile/dialog.js'))
		 ->appendFile($this->baseUrl('/js/mobile/vkNgine.js'));

$this->headMeta()
		->appendHttpEquiv('Content-Type', 'text/html; charset=UTF-8')
		->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
		->appendName('apple-mobile-web-app-capable', 'yes')
		->appendName('apple-mobile-web-app-status-bar-style', 'black')
		->appendName('viewport', 'user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0');

?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<?= $this->headTitle() . "\n"; ?>

<?= $this->headMeta() . "\n"; ?>
	
<?= $this->headLink()  . "\n"; ?>

<?= $this->headScript(). "\n"; ?>

</head>
		
<body vkNgine_version="<?= vkNgine_Version::VERSION; ?>">
	<div class="site">
		<?php echo $this->layout()->content; ?>
	</div>
	
    <?php if(vkNgine_Config::getSystemConfig()->settings->ga->enabled) : ?>	
	<script type="text/javascript">
	  var _gaq = _gaq || [];
	  _gaq.push(['_setAccount', '<?= vkNgine_Config::getSystemConfig()->settings->ga->code; ?>']);
	  _gaq.push(['_trackPageview']);
	
	  (function() {
	    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
	    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
	    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	  })();
	</script>
	<?php endif; ?>

</body>
</html>	