<?php
define('IN_DEVELOPMENT', APPLICATION_ENV === 'development');

echo $this->doctype() . "\n";

$this->headLink()
		->prependStylesheet($this->baseUrl('/js/public/bootstrap/css/bootstrap.min.css'))
		->headLink(array('rel' => 'icon', 'href' => $this->baseUrl('dumbbell.ico'), 'type' => 'image/x-icon', 'PREPEND'))
		->appendStylesheet($this->baseUrl('/css/font-awesome/css/font-awesome.css'))
		->appendStylesheet($this->baseUrl('/css/styles.css'))
		->appendStylesheet($this->baseUrl('/css/style_responsive.css'))
	 	->appendStylesheet($this->baseUrl('/css/style_default.css'))
	 	->appendStylesheet($this->baseUrl('/css/uniform/css/uniform.default.css'))
	 	->headLink(array('rel' => 'apple-touch-icon', 'href' => '/V.ico'));

$this->headScript()
	 	->prependFile($this->baseUrl('/js/jquery-1.8.2.min.js'))
	 	->appendFile($this->baseUrl('/js/public/bootstrap/js/bootstrap.min.js'))
	 	->appendFile($this->baseUrl('/js/public/jquery.blockui.js'))
	 	->appendFile($this->baseUrl('/js/public/dialog.js'))
	 	->appendFile($this->baseUrl('/js/form.js'))	 	 
	 	->appendFile($this->baseUrl('/js/public/vkNgine.js'));

$this->headMeta()
     	->appendHttpEquiv('Content-Type', 'text/html; charset=UTF-8')
		->appendHttpEquiv('expires', 'Oct, 31 Sun 1982 06:66:66 GMT')
		->appendHttpEquiv('pragma', 'no-cache')
		->appendHttpEquiv('Cache-Control', 'no-cache')
        ->appendName('apple-mobile-web-app-capable', 'yes')
		->appendName('apple-mobile-web-app-status-bar-style', 'black')
		->appendName('viewport', 'width=device-width, initial-scale=1.0');
?>

<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->
<!--[if !IE]><!--> <html lang="en"> <!--<![endif]-->

<head>

<?= $this->headTitle() . "\n"; ?>
<?= $this->headMeta() . "\n"; ?>
<?= $this->headLink()  . "\n"; ?>
<?= $this->headScript(). "\n"; ?>
	
</head> 

<body>
	<?php echo $this->layout()->content; ?>
</body>

</html>	