<div id="error" class="notification-box-red last-item notification-wrapper" style="display:none;margin-top:5px;">
     <a href="#" class="notification-quit-red notification">x</a>
     <img class="notification-icon" src="/images/mobile/lists/list-cross.png" alt="">
     <p class="notification-text"><?= $this->t->_('Access denied!'); ?></p>
</div> 
        
<div>
	<form action="/auth/login" method="<?= $this->form->getMethod(); ?>" enctype="<?= $this->form->getEncType(); ?>" name="<?= $this->form->getName(); ?>" id="<?= $this->form->getId(); ?>">
    <div class="decoration"></div>
        <fieldset>
        	<?= $this->form->username; ?>
            <?= $this->form->password; ?>
            <p align="center">
                <input type="submit" name="submitMessage" class="contactButton button grey" id="contactSubmitBtn" value="<?= $this->t->_('Login'); ?>"/>
            </p>
		</fieldset>
	</form>
    <div class="decoration"></div>
    <div align="center"><img src="/images/admin/vkn_v2_powered_by.png"></div>
</div>

<script>
	$("#username").focus();

	var options = {  
		url: '<?= $this->form->getAction(); ?>',
        success: loginHandler,
		dataType : 'json'
    };
    
	$('#<?= $this->form->getId(); ?>').ajaxForm(options);
</script>

