  <div class="logo">
		<img src="/dumbbell.png" alt="" /> 
  </div>
 
  <div class="content"> 
    <form id="<?= $this->form->getId(); ?>" action="<?= $this->form->getAction(); ?>" class="form-vertical login-form" name="<?= $this->form->getId(); ?>" method="post" enctype="application/x-www-form-urlencoded" >    		
       <h3 class="form-title"><?= $this->t->_('Login to your account'); ?></h3>
		<div class="alert alert-error hide">
			<button class="close" data-dismiss="alert"></button>
			<span></span>
		</div>	
 
      <div class="control-group">
      	<label class="control-label visible-ie8 visible-ie9"><?= $this->t->_('Username'); ?></label>
        <div class="controls">
          <div class="input-icon left">
          	<i class="icon-user"></i>
            <?= $this->form->username; ?>
          </div>
        </div>
      </div>
      
      <div class="control-group">
      	<label class="control-label visible-ie8 visible-ie9"><?= $this->t->_('Password'); ?></label>
        <div class="controls">
          <div class="input-icon left">
            <i class="icon-lock"></i>
          	<?= $this->form->password; ?>             
          </div>
        </div>
      </div>
      
      <div class="form-actions">
			<label class="checkbox">
			<input type="checkbox" name="remember" value="1"/> <?= $this->t->_('Remember me'); ?>
			</label>
			<button type="submit" class="btn green pull-right">
				<?= $this->t->_('Login'); ?> <i class="m-icon-swapright m-icon-white"></i>
			</button>            
		</div>
		
		<div class="forget-password">
				<h4><?= $this->t->_('Forgot your password?'); ?></h4>
				<p>
					<?= sprintf($this->t->_('Click %s to reset your password'), '<a href="javascript:;" class="" id="forget-password">' . $this->t->_('here') . '</a>'); ?>
					
				</p>
			</div>
      
    </form>
    
    <form class="form-vertical forget-form" action="">
		<h3 class=""><?= $this->t->_('Forget Password?'); ?></h3>
		<p><?= $this->t->_('Enter your e-mail address below to reset your password.'); ?></p>
		<div class="control-group">
			<div class="controls">
				<div class="input-icon left">
					<i class="icon-envelope"></i>
					<input class="m-wrap placeholder-no-fix" type="text" placeholder="Email" name="email" />
				</div>
			</div>
		</div>
		<div class="form-actions">
			<button type="button" id="back-btn" class="btn">
			<i class="m-icon-swapleft"></i> <?= $this->t->_('Back'); ?>
			</button>
			<button type="submit" class="btn green pull-right">
			<?= $this->t->_('Submit'); ?> <i class="m-icon-swapright m-icon-white"></i>
			</button>            
		</div>
	</form>
    
  </div>
  
  <div class="copyright">
    <img src="/css/admin/themes/vkNgine3/images/logo.png">
  </div>

<script>
	
</script>

