  <div id="logo" class="center"></div>
 
  <div id="login">
    
    <form action="/auth/login" method="post" enctype="application/x-www-form-urlencoded" name="publicFormLogin" id="publicFormLogin" class="form-vertical no-padding no-margin">
    
      <div class="control-group">
        <div class="controls">
          <div class="input-prepend">
            <span class="add-on"><i class="icon-user"></i></span><?= $this->form->username; ?>
          </div>
        </div>
      </div>
      
      <div class="control-group">
        <div class="controls">
          <div class="input-prepend">
            <span class="add-on"><i class="icon-lock"></i></span><?= $this->form->password; ?>             
          </div>
          <div class="block-hint pull-right">
            <a href="javascript:;" class="" id="forget-password"><?= $this->t->_('Forgot Password?'); ?></a>
          </div>
          <div class="clearfix space5"></div>
        </div>
      </div>
      <?= $this->form->submit; ?>
    </form>
    
    <form id="forgotform" class="form-vertical no-padding no-margin hide" action="">
      <p class="center">Enter your e-mail address below to reset your password.</p>
      <div class="control-group">
        <div class="controls">
          <div class="input-prepend">
            <span class="add-on"><i class="icon-envelope"></i></span><input id="input-email" type="text" placeholder="Email" />
          </div>
          <div class="block-hint pull-right">
            <a href="javascript:;" class="" id="forget-btn"><?= $this->t->_('Go back to login form'); ?></a>
          </div>
        </div>
        <div class="space10"></div>
      </div>
      <input type="button" id="forget-btn" onclick="alert('This feature has not built yet!');return false;" class="btn btn-block btn-inverse" value="Submit" />
    </form>
    
  </div>
  
  <div id="login-copyright">
    <img src="/css/admin/themes/vkNgine3/images/logo.png">
  </div>

<script>
	$("#username").focus();

	vkNgine.initLogin();

	var options = {  
		url: '<?= $this->form->getAction(); ?>',
        success: loginHandler,
		dataType : 'json'
    };
    
	$('#<?= $this->form->getId(); ?>').ajaxForm(options);
</script>

