<?php 
	$isLogged = vkNgine_Config::getSystemConfig()->settings->error_logging;	
	$logFile = vkNgine_Config::getSystemConfig()->settings->error_logfile;
?>

<div class="row-fluid">
	<div class="span11 page-500">
		<a class="glyphicons no-js circle_exclamation_mark" href="#">
			<i></i>
		</a>
		
		<h2><?= $this->message; ?></h2>
		
		<div class=" details">
			<p>
				<label><strong><?= $this->t->_('Message'); ?></strong></label>
				<pre><?= $this->exception->getMessage(); ?></pre>
			</p>
			
			<?php if($isLogged): ?>
			<p>
				<label><strong><?= $this->t->_('Logging'); ?></strong></label>
				<pre>This error was logged to <i>`<?= $logFile; ?>`</i></pre>
			</p>
			<?php endif; ?>
			
			<p>
				<label><strong><?= $this->t->_('Request Parameters'); ?></strong></label>
				<pre><?= print_r($this->request->getParams(), 1); ?></pre>
			</p>
			
			<p>
				<label><strong><?= $this->t->_('Trace'); ?></strong></label>
				<pre><?= $this->exception->getTraceAsString(); ?></pre>
			</p>
			
			<div class="menu">
				<p>					
					<a class="btn blue btn-block" href="<?= $this->publicUrl(); ?>">
						<?= $this->t->_('Home'); ?>
						<i class="m-icon-swapleft m-icon-white"></i>
					</a>	
				</p>
			</div>
		</div>
	</div>
</div>
