<div class="row-fluid">
	<div class="span11 page-500">
		<h3><?php echo $this->message; ?></h3>
		<div class=" details">
			<h6><?php echo $this->exception->getMessage(); ?></h6>
			<p>
				<pre><?php echo $this->exception->getTraceAsString(); ?>
				<?php echo print_r($this->request->getParams(), 1); ?>
				</pre>
			</p>
			
			<div class="menu">
				<a href="<?= $this->publicUrl(); ?>">home</a>
			</div>
		</div>
	</div>
</div>
